= GM/T 0015-2012 SM2 Cryptographic Algorithm Application Specification
:docnumber: 0015
:edition: 1
:revdate: 2012-11-22
:copyright-year: 2012
:language: en
:script: Latn
:title-main-zh: 基于SM2密码算法的数字证书格式规范
:title-main-en: Digital certificate format based on SM2 algorithm
:published-date: 2012-11-22
:implemented-date: 2012-11-22
:technical-committee-type: technical
:library-ics: 35.040
:library-ccs: L80
:scope: sector
:topic: method
:prefix: GM/T
:mandate: recommended
:library-ics: 35.040
:library-ccs: L80
:proposer: State Cryptography Administration
:authority: State Cryptography Administration
:stem:

:sectnums!:

.Foreword

This Standard is drafted in accordance with the rules of GB/T 1.1--2009.

Please be informed that part of this Standard may involve patterns. The issuer of this Standard shall not bear the responsibility for identifying those patterns.

Annex A, Annex B and Annex C are normative annexes; Annex D is informative annex.

This Standard is proposed by and shall be under the jurisdiction of State Cryptography Administration.

Drafting Committee: Shanghai Koal Software Co., Ltd., Beijing Certificate Authority Co., Ltd., Beijing Haitai Fangyuan Technology Co., Ltd., Wuxi Jiangnan Information Security Engineering Technology Center, Shanghai Electronic Certificate Authority Center Co., Ltd., Changchun Jida Zhengyuan Information Technology Co., Ltd., Westone Information Technology Inc., Xingtang Communications Technology Co., Ltd., Beijing Huada Zhibao Electronic System Co., Ltd., Shandong De'an Technology Co., Ltd., National Information Security Engineering Center, National Cryptography Administration Commercial Cryptography Testing Center.

Drafters: Ping Liu, Wuzheng Tan, Shusheng Li, Zengshou Liu, Qiang Xu, Cheng Liu, Lili Zhao, Yuanzheng Li, Nina Wang, Yue Chen, Fanyu Kong, Feng Yuan, Zhiwei Li.

The algorithms involved in this Standard shall be used in accordance with the requirements of the State Cryptography Administration.




:sectnums:
[[scope]]
== Scope

This standard specifies the basic structure and data content of a digital certificate and a certificate revocation list.

This standard is applicable to the research and development of a digital certificate authentication system, the operation of a digital certificate authority, and the application security based on a digital certificate.

[bibliography]
== Normative references

* [[[GBT162648,GB/T 16264.8]]], _Information Technology -- Open System Interconnection Directory Section 8: Public Key and Attribute Certificate Frameworks_
* [[[GMT0006,GM/T 0006]]], _Cryptographic Application Identifier Criterion Specification_
* [[[GMT0009,GM/T 0009]]], _SM2 Cryptography Algorithm Application Specification_
* [[[GMT0010,GM/T 0010]]], _SM2 Cryptography Message Syntax Specification_
* [[[P<<GBT162648>>,PKCS #7]]], _Cryptographic Message Syntax Standard_
* [[[RFC5280,RFC 5280]]], _Internet X.509 Public Key Infrastructure Certificate and Certificate Revocation List (CRL) Profile_


[[terms]]
== Terms and definitions

=== [zh]#数字证书# [en]#digital certificate#

credible digital file digitally signed by an authoritative, credible, and impartial state-approved third-party certificate authority (CA).

=== [zh]#证书撤销列表# [en]#certificate revocation list#
[alt]#CRL#

list of revoked certificates issued by CA.

=== [zh]#CA 证书# [en]#CA certificate#

certificate issued to a digital certificate authority.

=== [zh]#终端实体证书# [en]#entity certificate#

also known as User Certificate, is a personal certificate, an authority certificate, a device certificate, etc. signed and issued by a digital certificate authority


== Abbreviations

The following abbreviations apply to this document.

CA::  Certificate Authority
CRL:: Certificate Renovation List
DIT:: Directory Information Tree
OID:: Object Identifier
PKI:: Public Key Infrastructure


== Digital Certificate and CRL

=== Overview

Digital Certificate has the following characteristics:

* Any user capable of obtaining and using the public key of a certificate authority can recover the public key authenticated by the certificate authority.
* No other authorities are able to change a certificate, except for the certificate authority that certifies the certificate. Certificates are unforgeable.

Since certificates are unforgeable, they can be published by being placed in a directory, without the need of being specially protected in the future.

NOTE: Despite the use of a unique name in DIT for the explicit definition of CA, CA and DIT have no connections.

Certificate authorities generate user certificates by signing information sets. An information set includes a distinguishable user name, a public key, and an optional unique identifier containing additional user information. The exact format of the unique identifier content is not specified in this chapter but is left to CA to define. Unique identifiers can be other forms such as object identifiers, certificates, dates, or certificates that describe the validity of distinguishable user names. To be specific, if a user certificate has a distinguishable name of A and a unique identifier of UA, and is generated by a certificate authority with the name of CA and the unique identifier of UCA, the user certificate has the following form:

[stem]
----
CA<<A>> = CA{V, SN, AI, CA, UCA, A, UA, Ap, TA}
----

Where V indicates certificate version; SN indicates certificate serial number; AI indicates the algorithm identifier used to sign the certificate; UCA indicates CA's optional unique identifier; UA indicates User A's optional unique identifier; Ap indicates User A's public key; TA indicates certificate validity consisting of two dates, the time period between which is the validity of the certificate. Certificate validity is a time interval, during which CA must ensure to maintain the certificate information status, that is to release revocation information data. Since TA is assumed to change within a period cycle of no less than 24 hours, Coordinated Universal Time is required as the system reference time. The signature on the certificate can be used to verify the validity of the certificate by any user who knows the CA public key CAp.

CRL is a list file of revoked certificates. This list can be applied on an application system to determine the validity of user certificates. CRL complies with the certificate revocation list format of the X.509V2 standard.



=== Digital Certificate Format

==== General

This Standard uses distinguished encoding rules (DER) of GB/T 16262 series of standards to encode the information in the following certificate, forming a specific certificate data structure. ASN.1 DER encoding is an encoding system of each element's tag, length and value.

==== Data Structure of Basic Certificate Domain

The basic data structure of the digital certificate is as follows:

[source,asn1]
----
Certificate ::= SEQUENCE {
  tbsCertificate      TBSCertificate,
  signatureAlgorithm  AlgorithmIdentifier,
  signatureValue      BIT STRING }
----

// TODOB: DEFAUT is a TYPO in the original standard!

[source,asn1]
----
TBSCertificate ::= SEQUENCE {
  version            [0] EXPLICIT Version DEFAUT v1,
  serialNumber          CertificateSerialNumber,
  signature             AlgorithmIdentifier,
  issuer                Name,
  validity              Validity,
  subject               Name,
  subjectPublicKeyInfo  SubjectPublicKeyInfo,
    issuerUniqueID   [1] IMPLICIT UniqueIdentifier OPTIONAL,
                                --If present, version must be v2 or v3

  subjectUniqueID    [2] IMPLICIT UniqueIdentifier OPTIONAL,
                                --If present, version must be v2 or v3

  extensions         [3] EXPLICIT Extensions OPTIONAL --Extentions
                                --If present, version must be v3
}

Version ::= INTEGER {  v1(0)  ,y2(1) ,v3(2)  }

CertificateSerialNumber ::= INTEGER

Validity ::= SEQUENCE {
  notBefore      Time,
  notAfter      Time }

Time ::= CHOICE {
  utcTime        UTCTime,
  generalTime    GeneralizedTime }

UniqueIdentifier ::= BIT STRING SubjectPublicKeyInfo ::= SEQUENCE {
  algorithm          AlgorithmIdentifier,
  subjectPublicKey  BIT STRING }

Extensions ::= SEQUENCE SIZE (1..MAX) OF Extension

Extension ::= SEQUENCE {
  extnID        OBJECT IDENTIFIER,
  critical      BOOLEAN DEFAULT FALSE,
  extnValue     OCTET STRING }
----


The data structure of the above certificate is composed of three domains: tbsCertificate，signatureAlgorithm, and signatureValue. The meanings of the domains are as follows:

* tbsCertificate domain contains subject name, issuer name, subject's public key, certificate validity and other related information.

* signatureAlgorithm domain contains the cryptographic identifier used by a certificate authority to issue this certificate. An algorithm identifier's ASN.1 structure is as follows:
+
[source]
----
AlgorithmIdentifier ::= SEQUENCE {
  algorithm     OBJECT IDENTIFIER,
  parameters    ANY DEFINED BY algorithm OPTIONAL }
----
+
Algorithm identifier is used to identify a cryptographic algorithm, in which OBJECT IDENTIFIER identifies the specific algorithm. The content of optional parameters completely relies on the algorithm identified. The algorithm identifier of this domain must be the same as the signature algorithm item identified by the signature in tbsCertificate. If the signature algorithm is SM2, no parameters are involved.

* signatureValue domain contains the result of tbsCertificate being digitally signed. ASN.1 DER encoded tbsCertificate is used as the input of a digital signature, while the result of the signature is encoded as BIT STRING type according to ASN.1 and saved in the certificate signature range.
+
If the signature algorithm is SM2, please see <<GMT0009>> for SM2 cryptographic algorithm signature data format.

==== TBSCertificate and its data structure

TBSCertificate contains the first ten information items of a certificate structure, including subject name, issuer name, subject's public key, validity, version number and serial number; some TBSCertificates may also contain optional unique identifiers and extensions. The syntax and semantics of the above items are defined in the following paragraphs of this section.

===== Version

This item describes the version number of an encoded certificate.


[[tbs-serial]]
===== serial number

This item is a positive integer assigned to each certificate by a CA. The serial number of each certificate issued by a CA must be unique (so that a certificate can be uniquely identified by the issuer's name and serial number). A CA must ensure a serial number is a non-negative integer. A serial number can be a long integer. A certificate user must be able to handle up to 20 8-bit byte serial number values. A CA must ensure not to use serial numbers greater than 20 8-bit bytes.

===== signature

This item contains cryptographic algorithm identifier used by a CA to issue this certificate. This algorithm identifier must be the same as the algorithm identifier of the signatureAlgorithm item in the certificate. The content of optional parameters completely relies on the specific algorithm identified and can support the user-defined signature algorithm.


[[tbs-issuer]]
===== Issuer

This item identifies the entity that signs and issues a certificate. It must contain a non-null distinguished name (DN-distinguished name). This item is defined as Name type, with the following ASN.1 structure:

[source]
----
Name          ::= CHOICE { RDNSequence }
RDNSequence   ::= SEQUENCE OF RelativeDistinguishedName
RelativeDistinguishedName   ::= SET OF AttributeTypeAndValue
AttributeTypeAndValue       ::= SEQUENCE {
  type    AttributeType,
  value   AttributeValue }
AttributeType   ::= OBJECT IDENTIFIER
AttributeValue  ::= ANY DEFINED BY AttributeType
DirectoryString ::= CHOICE {
  teletexString       (SIZE (1..MAX)),
  printableString     PrintableString (SIZE (1..MAX)),
  universalString     (SIZE (1..MAX)),
  utf8String          UTF8String (SIZE (1..MAX)),
  bmpString           BMPString (SIZE (1..MAX)) }
----

Name describes the names of the hierarchical structures composed of certain attributes, for example, country name and its corresponding value, "`C=CN`". The type of AttributeValue is determined by AttributeType, which is usually a DirectoryString type. DirectoryString type is defined as one of the following types: PrintableString, TeletexString，BMPString，UTF8String and UniversalString. UTF8String encoding is preferred.

===== validity

This item is a time period, during which CA guarantees to maintain the information about the status of a certificate. This item is represented as a SEQUENCE type data with two time values: a certificate validity starting time (notBefore) and a certificate validity ending time (notAfter). Both NotBefore and NotAfter can be encoded as either the UTCTime type or the GeneralizedTime type.

[level=6]
===== Encoding Type Requirements

A CA complying with this Standard must encode time as the UTCTime type before 2049 (including 2049) and as the GeneralizedTime type after 2050.

[[validity-utctime]]
[level=6]
===== UTCTime

This item is a standard ASN. 1 type set up for international applications. In this item, only local time is not enough. UTCTime determines years using two low order digits and is accurate to 1min or 1s. UTCTime contains Z (for Zulu, or Greenwich Mean Time) or time difference.

In this item, the UTCTime value must be expressed in Greenwich Mean Time (Zulu), and must include seconds, even if the second value is zero (that is, time format is YYMMDDHHMMSSZ). The system must interpret a year field (YY) as follows:

When YY is greater than or equal to 50 years, the year shall be interpreted as 19YY; when YY is less than 50 years, the year shall be interpreted as 20YY.

[[validity-generalizedtime]]
[level=6]
===== GeneralizedTime

This item is a standard ASN. 1 type, representing the variable precision of time. A GeneralizedTime field is capable of containing a time difference between a local time and a Greenwich Mean Time.

In this item, a GeneralizedTime value must be expressed in Greenwich Mean Time, and must contain seconds, even if the second value is zero (that is, time format is YYYYMMDDHHMMSSZ). The GeneralizedTime value must not contain fractional seconds.

===== subject

This item describes the entity corresponding to the public key in the subject public key item. Subject name can appear in a subject item and/or a subject alternative name extension (subjectAltName). If the subject is a CA, the subject item must be a non-null distinguished name matching the content of the issuer item. If the subject naming information only appears in a subject alternative name extension (for example, the key is bound to only one Email address or one URL), the subject name must be a null sequence, and the subject alternative name extension must be identified as critical.

When a subject item is non-null, the item must contain a distinguished name (DN). The distinguished name of each subject entry authenticated by a CA must be unique. A CA can issue multiple certificates with the same distinguished name for one subject entry.

Subject name extension is defined as the name type of ISO/IEC 9594-2:2001.


[[subject-public-key-info]]
===== Subject Public Key Info

This item is used to identify a public key and the corresponding public key algorithm. The public key algorithm is expressed using the structure of the algorithm identifier AlgorithmIdentifier.

When a public key algorithm is RSA, please see PKCS# 7 for the definition of an AlgorithmIdentifier structure; when a public key algorithm is SM2, please see <<GMT0010>> for the definition of an AlgorithmIdentifier structure.


===== IssuerUniqueID

This item is mainly used to deal with the reuse issue of a subject name or an issuer name. This Standard suggests the names of different entities should not be reused. Internet certificates should not use unique identifiers. Certificate authorities complying with this Standard should not generate a certificate with the issuer's unique identifier but should be able to resolve this item and make a comparison in the application process.

===== SubjectUniqueID

This item is mainly used to deal with the reuse issue of subject name. This Standard suggests the names of different entities should not be reused and does not suggest using this item. A certificate authority complying with this Standard should not generate a certificate with the subject's unique identifier but should be able to resolve the unique identifier and make a comparison in the application process.

===== extensions

// TODO: This is an error, it should point to 5.2.4 instead of 5.2.3
//本项是一个或多个证书扩展的序列 (SEQUENCE),其内容和数据结构在5.2.3中定义。

This item is a sequence (SEQUENCE) of one or more certificate extensions. The content and data structure of this item are defined in <<cert-extensions>>.

[[cert-extensions]]
==== Certificate Extension Domain and Data Structure

===== Certificate Extension


The certificate extensions defined in this Standard provide the method that connects some additive attributes with a user or a public key, as well as the method of certificate structure management. Digital certificate allows defining a standard extension and a special extension. Each extension in a certificate can be designated as critical or non-critical. An extension consists of three parts: an extension type, an extension criticality and an extension value. Extension criticality tells a certificate user whether a certain extension type can be ignored. If a certificate's application system cannot recognize a critical extension, the certificate must be rejected. If a certificate's application system cannot recognize a non-critical extension, the information of this extension can be ignored.

This section defines some standard extensions. What calls for special attention is that the use of a critical extension in practical application process can result in the unavailability of this certificate in some general-purpose applications.

Each extension consists of an object identifier OID and an ASN. 1 structure. When an extension appears in a certificate, OID exists as extnID, the corresponding ASN.1 encoding structure of which is the value of the 8-bit string extnValue. A specific extension in a specific certificate can only appear once. For example, one certificate can only include one authority key identifier extension. A Boolean value is included in an extension to indicate the criticality of this extension. Its default value is FALSE, namely non-critical. The text of each extension indicates the acceptable value of a key item.

The CA complying with this Standard must support the following extensions: key identifier, basic constraint, key usage, certificate polity, etc. If the subject item in a CA-issued certificate is a null sequence, this CA must support a subject alternative name extension. Other extensions are optional. A CA can also support other extensions not defined in this Standard. A certificate issuer must notice that the designation of those extensions as critical can present barrier to the interoperability.

The application complying with this Standard must be capable of recognizing key usage, certificate policy, subject alternative name, basic constraint, name constraint, policy constraint, and key usage of extension. Furthermore, this Standard can also support authority, subject key identifier, as well as policy mapping extension.



===== Standard Extension

[level=6]
===== General

This section defines the standard certificate extension of a digital certificate. Each extension is related to an OID designated in <<GBT162648>>. Those OIDs are all id-ce members, with the following definition:

[source]
----
id-ce   OBJECT IDENTIFIER   ::=   {  joint-iso-ccitt(2) ds(5) 29 }
----

[level=6]
===== authorityKeyIdentifier

An authority key identifier extension provides a way to identify the public key corresponding to the certificate signature private key. This extension is used when issuer has multiple keys coexisting or multiple signing keys due to changes occurring to issuer. The identification can be based on either the subject key identifier in the issuer's certificate or the issuer's name and serial number.

All corresponding certificates generated by a CA should include keyIdentifier of the authorityKeyIdentifier extension to facilitate the chain establishment. When a CA releases its public key in the form of a self-signed certificate, the authority key identifier can be omitted. In this case, the subject and the authority key identifier are completely identical.

This item can be used as either a certificate extension or a CRL extension. This identifier is used to verify the public key signed on a certificate or a CRL. It can identity different keys used by the same CA (for example, when key updates occur).


[level=7]
===== Definition

[source]
----
id-ce-authorityKeyIdentifier OBJECTIDENTIFIER   ::= {id-ce 35}

AuthorityKeyIdentifier ::= SEQUENCE {
  KeyIdentifier                [0] KeyIdentifier  OPTIONAL,
  authorityCertIssuer          [1] GeneralNames OPTIONAL,
  authorityCertSerialNumber   [2] CertificateSerialNumber OPTIONAL }

(WITH COMPONENTS  {..., authorityCertIssuer PRESENT,
authorityCertSerialNumber PRESENT} |
WITH COMPONENTS  {...，authorityCertIssuer ABSENT,
authorityCertSerialNumber ABSENT})

KeyIdentifier ::= OCTET STRING
----

[level=7]
===== Specification

A KeyIdentifier value should be exported from the public key used to verify a certificate signature or from the method that generates the unique value. KeyIdentifier of a public key can be generated using the following two general methods:

[loweralpha]
. keyIdentifier consists of the hash value of 160-bit SHA-1 of BIT STRING subjectPublicKey (minus tag, length, and several unused bytes);
. keyIdentifier consists of 0100 followed by the lowest 60 bits of SHA-1 hash value of BIT STRING subjectPublicKey.

This key can be identified by the key identifier in the keyIdentifier field, or by the identifier of this key certificate (given the certificate issuer in the authorityCertIssuer field and the certificate serial number in the authorityCertSerialNumber field), or by the key identifier and the certificate identifier of this key. If two forms of identifier are used, then the issuer of the certificate or the CRL should ensure the two forms are consistent. Each key identifier shall be unique for all key identifiers of a CRL and for a certificate containing extensions from an issuing authority. The implementation that supports this extension is not required to process all name forms in the authorityCertIssuer field.

A certificate authority designates or automatically generates a certificate serial number, so that the combination of an issuer and a certificate serial number can uniquely identify a certificate.

All certificates must contain this extension as well as the keyIdentifier field, except for a self-signed certificate. If the SubjectKeyIdentifier extension is included in a certificate issuer's certificate, this extension's keyIdentifier must be consistent with the SubjectKeyIdentifier extension value of the certificate issuer's certificate. A SubjectKeyIdentifier extension can be generated using either method mentioned above if it is not included in a certificate issuer's certificate.

keyIdentifier and authorityCertSerialNumber are suggested to be required, but this extension must be non-critical.



[level=6]
===== subjectKeyIdentifier

This item provides a method to identify a certificate containing a particular public key. This extension identifies an authenticated public key. It can distinguish different keys used by the same subject (for example, when key update occurs).

[level=7]
===== Definition

[source]
----
id-ce-subjectKeyIdentifier OBJECT IDENTIFIER  ::= { id-ce 14 }
SubjectKeyIdentifier  ::= KeyIdentifier
----

[level=7]
===== Specification


对于使用密钥标识符的主体的各个密钥标识符而言，每一个密钥标识符均应是唯一的。此扩展项总是非关键的。

所有的CA 证书必须包括本扩展；而且CA 签发证书时必须把 CA  证书中本扩展的值赋给终端实体证书 AuthorityKeyIdentifier 扩展中的 KeyIdentifier项。CA 证书的主体密钥标识符应从公钥中或者生成唯一值的方法中导出。终端实体证书的主体密钥标识符应从公钥中导出，有两种通用的方法从公钥中生成密钥标识符 (See <<subject-public-key-info>>）。


[level=6]
===== KeyUsage

This item specifies the usage of an authenticated public key.

[level=7]
===== Definition

[source]
----
id-ce-keyUsage OBJECT IDENTIFIER ::= { id-ce 15 }
KeyUsage ::= BIT STRING {
  digitalSignature    (0),
  nonRepudiation     (1),
  keyEncipherment    (2),
  dataEncipherment   (3),
  keyAgreement       (4),
  keyCertSign       (5),
  cRLSign           (6),
  encipherOnly       (7),
  decipherOnly      (8) }
----

[level=7]
===== Specification

The usages of KeyUsage are as follows:

[loweralpha]
. digitalSignature: verify the digital signatures not identified in the usages of the following b), f), or g):

. nonRepudiation: verify the digital signatures used to provide a non-repudiation service. This service prevents a signing entity from falsely rejecting an action (not including, such as the certificates of f) or g) or a CRL signature);

. KeyEncipherment: private key or other security information; for example, the usage of a key exchange;

. dataEncipherment: enciphers user data but doesn't include the key of c) mentioned above or other security information.

. keyAgreement: used as a public key during key agreement.

. keyCertSign: used for verify a certificate's CA signature.

. cRLSign: verify a CRL's CA signature.

. encipherOnly: When this bit is used with the keyAgreement bit that has been set, the public key negotiation key is only used for enciphering data (the definition of this bit being used with other key usage bit is not defined).

. decipherOnly: When this bit is used with the keyAgreement bit that has been set, the public key negotiation key is only used for deciphering data (the definition of this bit being used with other key usage bit is not defined).


keyCertSign is only used in a CA certificate. If KeyUsage is set as keyCertSign and coexists with a basic constraint extension in the same certificate, then the value of this CA extension should be TRUE. A CA can also use other key usage bits defined in keyUsage, for example, to provide digitalSignature for authentication and online management of transaction integrity.

If the keyAgreement bit is missing, this Standard doesn't define the encipherOnly bit. If the encipherOnly bit is confirmed, and the keyAgreement bit is also confirmed, the subject public key can be only used for encrypted data; meanwhile, execute the key agreement.

If the keyAgreement bit is not set, the decipherOnly bit is not defined. If the decipherOnly bit is confirmed, and the keyAgreement bit is also confirmed, the subject public key can be only used for decrypted data; meanwhile, execute the key agreement.

All CA certificates must include this extension and must contain the usage of keyCertSign. This extension can be defined as either critical or non-critical, depending on the choice of the certificate issuer.

If this extension is marked as critical, then this certificate should only apply to the corresponding key usage location of "`1`".

If this extension is marked as non-critical, then it indicates the intended usage or other various usages of this key and can be used to lookup the correct key/certificate of the entity with multiple keys/certificates. It is an advisory item and does not indicate the usage of this key is limited to the designated usage. A "`0`" bit indicates this key is not for the intended usage. If all bits are "`0`", it indicates this key has another certain usage other than the usages listed.

In application, this extension is used to distinguish certificate types. When one of c), d), h) and i) bits is set, the certificate is an encryption certificate; when one of a) and b) bits is set, the certificate is a signature certificate.



[level=6]
===== extKeyUsage

This item indicates that authenticated public keys can have one or more usages. They can function as a supplement or substitute for the basic usage of a key usage extension.

[level=7]
===== Definition

// TODO: original document missing "="
// id-ce-extKeyUsage OBJECT IDENTIFIER ：： {id-ce 37}
//

[source]
----
id-ce-extKeyUsage OBJECT IDENTIFIER   ::= {id-ce 37}
ExtKeyUsageSyntax ::= SEQUENCE SIZE (1..MAX) OF KeyPurposeId
KeyPurposeId      ::= OBJECT IDENTIFIER
----


[level=7]
===== Specification


The usage of a key can be defined by any organization with the need of the key usage. The object identifier used to identify a key usage should be distributed according to GB/T 17969.1—2000.

This extension can be critical or non-critical, depending on the decision of the certificate issuer.

If this extension is marked as critical, this certificate should only be used for one of the designated usages.

If this extension is marked as non-critical, then it indicates the intended usage or other usages of this key and can be used to lookup the correct key/certificate of the entity with multiple keys/certificates. It is an advisory item and does not indicate the authority limits the usage of this key to the designated usage. However, the certificate for an application can still require a particular usage to be designated, so that this certificate can be accepted by this application.

If a certificate contains the critical key usage item and the critical extension key item, then the two items should process independently, and the certificate should only apply to the usage consistent with the two items. If no usages consistent with the two items exist, then this certificate cannot apply to any usage.

This Standard defines the following key usages:

[source]
----
id-kp OBJECT IDENTIFIER ::= { id-pkix 3 }
id-kp-serverAuth OBJECT IDENTIFIER ::= { id-kp 1 }
----

* TLS Web server identification

* Key usage can be set as digitalSignature, keyEncipherment or keyAgreement

[source]
----
id-kp-clientAuth OBJECT IDENTIFIER ::= { id-kp 2 }
----

* TLS Web server identification

* Key usage can be set as digitalSignature and/or keyAgreement

[source]
----
id-kp-codeSigning OBJECT IDENTIFIER ::= { id-kp 3 }
----

* can download the executable code signature.
* Key usage can be set as digitalSignature

[source]
----
id-kp-emailProtection OBJECT IDENTIFIER ::= { id-kp 4 }
----

* E-mail protection
* Key usage can be set to digitalSignature, nonRepudiation and/or (keyEncipherment or keyAgreement）

[source]
----
id-kp-timeStamping OBJECT IDENTIFIER ::= { id-kp 8 }
----

* Bind object hash value to the time provided by the same time source
* Key usage can be set to digitalSignature, nonRepudiation

[source]
----
id-kp-OCSPSigning OBJECT IDENTIFIER ::= { id-kp 9 }
----

* OCSP response signature
* Key usage can be set to digitalSignature, nonRepudiation

[level=6]
===== privateKeyUsagePeriod

This item indicates the usage validity period of the private key corresponding to the authenticated public key. It can only be used for a digital signature key.

[level=7]
===== Definition

[source]
----
id-ce-privateKeyUsagePeriod OBJECT IDENTIFIER ::= { id-ce 16 }
PrivateKeyUsagePeriod ::= SEQUENCE {
  notBefore     [0] GeneralizedTime OPTIONAL,
  notAfter      [1] GeneralizedTime OPTIONAL}
----

[level=7]
===== Specification

The notBefore field indicates the earliest date and time when a private key is applied to a signature. Without the notBefore field, the starting time of a private key validity period is not available. The notAfter field indicates the latest date and time when a private key can be applied to a signature. Without the notAfter field, the ending time of a private key validity period is not available.

This extension is always non-critical.


NOTE: The validity of a private key can be different from the validity of the authenticated public key designated by the certificate validity period. As for a digital signature private key, the validity of a signed private key is usually shorter than the time of authenticating a public key.

NOTE: The verifier of a digital signature wants to check if this key is still not revoked until the moment of authentication. For example, due to a compromised key, the certificate should still be valid for the public key when being authenticated. After the public key expires, the verifier of the signature cannot rely on the protocol ruled by the CRL.


[level=6]
===== certificatePolicies

This item lists the certificate policies approved by an issuer CA. These policies apply to certificates and the optional qualifier information regarding those certificate policies.

The certificatePolicies extension contains a series of policy information entries; every entry has an OID and an optional qualification. This optional qualification can't change the definition of the policy.

In user certificates, these policy information entries describe the certificate issuing policies and the certificate application purposes. In a CA certificate, these policy entries set out the verifying paths and the policy sets of this certificate. The application system with specific policy requirements should have the policy list they are about to accept and compare the policy OID in the certificate with this list. If this extension is critical, then a path validity software must be able to explain this extension (including choose a top qualifier); otherwise it must reject this certificate.

In order to improve interoperability, this Standard suggests a policy information entry only contains one OID. If one OID is not enough, it is suggested to use the qualifiers designated in this item.

[level=7]
===== Definition

[source]
----
id-ce-certificatePolicies OBJECT IDENTIFIER ::= { id-ce 32 }

certificatePolicies ::= SEQUENCE SIZE (1..MAX) OF PolicyInformation

PolicyInformation ::= SEQUENCE{
  policyIdentifier    CertPolicyId,
  policyQualifiers    SEQUENCE SIZE (1..MAX) OF
                        PolicyQualifierInfo OPTIONAL}

CertPolicyId ::= OBJECT IDENTIFIER

PolicyQualifierInfo ::= SEQUENCE{
  policyQualifierId   PolicyQualifierId,
  qualifier            ANY DEFINED BY policyQualifierId }

--policyQualifierlds for Internet policy qualifiers

id-qt            OBJECT IDENTIFIER ::= { id-pkix 2 }
id-qt-cps        OBJECT IDENTIFIER ::= { id-qt  1  }
id-qt-unotice    OBJECT IDENTIFIER ::= { id-qt  2  }
PolicyQualifierId ::= OBJECT IDENTIFIER ( id-qt-cps | id-qt-unotice)

Qualifier ::= CHOICE {
  cPSuri        CPSuri,
  userNotice    UserNotice }

CPSuri    ::= IA5String

UserNotice  ::= SEQUENCE {
  noticeRef      NoticeReference OPTIONAL,
  explicitText  DisplayText OPTIONAL }

NoticeReference ::= SEQUENCE {
  organization    DisplayText,
  noticeNumbers   SEQUENCE OF INTEGER }

DisplayText ::= CHOICE {
  visibleString    VisibleString (SIZE (1..200)),
  bmpString        BMPString (SIZE (1..200)),
  utf8String      UTF8String  (SIZE (1..200)) }
----

[level=7]
===== Specification


This item defines two policy qualifiers for the use of certificate policy makers and certificate issuers. The qualifier types are CPS Pointer and User Notice.

The CPS Pointer qualifier contains a CPS (Certification Practice Statement) issued by a CA. The indicator form is URL.

User notice has two optional fields: the noticeRef field and the explicitText field. The noticeRef field names a group and identifies a special text declaration made by this group using notation. The explicitText field directly includes a text declaration in the certificate; this field is a string with no more than 200 characters. If noticeRef and explicitText are both in the same qualifier, and if an application software can find the announcement text designated by noticeRef, this text should be shown; otherwise the explicitText string should be shown.




[level=6]
===== policyMappings

This item only applies to a CA certificate. It lists one or more OID pairs. Each pair includes an issuerDomainPolicy and a subjectDomainPolicy. This pairing form indicates the issuer CA thinks its issuerDomainPolicy is equivalent to the subjectDomainPolicy of the subject CA. The user of the issuer CA can accept an issuerDomainPolicy for a certain application. Policy mapping tells the user of the issuer CA which policies related to the CA can be equivalent to the policies they accept.


[level=7]
===== Definition

[source]
----
id-ce-policyMappings OBJECT IDENTIFIER ::= { id-ce 33 }

PolicyMappingsSyntax ::= SEQUENCE SIZE(1..MAX) OF SEQUENCE{
  issuerDomainPolicy    CertPolicyId,
  subjectDomainPolicy    CertPolicyId}
----

[level=7]
===== Specification

Policy cannot be mapped to or come from the specific value anyPolicy.

This extension can be supported by the CA and/or the application. A certificate issuer can choose this extension to be either critical or non-critical. This Standard recommends critical; otherwise a certificate user cannot correctly interpret the published rules set by the CA.

NOTE: One example of policy mapping: The US government has a policy named the Canada Trade. The Canadian government has a policy named the US Trade. When the two policies can be differently identified and defined, the two governments can have such agreement: within the implicit rules of the two policies, the certification path is allowed to extend across the borderline.

NOTE: Policy mapping indicates making related decision can consume significant management expenses and involve a considerable amount of labor and appointed people. Generally speaking, the best way is to agree to use a global public policy that has a wider mapping than the application policy. In the above example, the best scenario is that the US, Canada and Mexico agree a public policy for the North American trade.

NOTE: Projected policy mapping can only be used in limited environments with very simple policy declarations.


[level=6]
===== subjectAltName


This item contains one or more alternative names (can use any one of the multiple name forms) for the use of an entity. The CA binds this entry to the authenticated public key.

The subject alternative name extension allows adding the attached identity to the certificate subject. The defined options include the Internet Email address, the DNS name, the IP address and the uniform resource identifier (URI), along with some purely locally defined options. Multiple name forms and multiple examples of each name form can be included. When such identify is attached to a certificate, a user-select name extension or an issuer-select name extension must be used. Since the subject alternative name is considered to be bound to the public key, all parts of the subject alternative name must be certified by the CA.




[level=7]
===== Definition

[source]
----
id-ce-subjectAltName OBJECT IDENTIFIER ::= { id-ce 17 }

SubjectAltName  ::= GeneralNames
GeneralNames    ::= SEQUENCE SIZE(1..MAX) OF GeneralName
GeneralName     ::= CHOICE{
  otherName                    [0]   OtherName,
  rfc822Name                  [1]   IA5String,
  dNSName                      [2]   IA5String,
  x400Address                  [3]   ORAddress,
  directoryName                [4]   Name,
  ediPartyName                [5]   EDIPartyName,
  uniformResourceIdentifier    [6]   IAS String,
  iPAddress                    [7]   OCTET STRING,
  registeredID                [8]   OBJECT IDENTIFIER }

OTHERNAME ::= SEQUENCE {
  type-id          OBJECT IDENTIFIER,
  value        [0] EXPLICIT ANY DEFINED BY type-id }

EDIPartyName::= SEQUENCE{
  nameAssigner    [0]  DirectoryString  OPTIONAL,
  partyName        [1]  DirectoryString  }
----

[level=7]
===== Specification

The alternative values in GeneralName type are the names of the following forms:

* otherName is the name of any form defined according to the OTHER-NAME information object class instance;

* rfc822Name is the Internet email address defined according to Internet RFC822;

* dnsName is the Internet domain name defined according to RFC 1034.

* x400Address is the O/R address defined according to GB/T 16284. 4—1996.

* directoryName is the directory name defined according to ISO/IEC 9594-2:2001.

* ediPartyName is the form name agreed on by both communicating parties of electronic data exchange. The nameAssigner component identifies the authority distributing the unique name value in partyName.

* uniformResourceldentifier is the URL syntax and encoding rules defined in UniformRAe-sourceIdentifier, RFC1738 used for WWW according to Internet RFC1630.

* iPAddress is the Internet Protocol address represented with binary strings according to Internet RFC791.

* registeredID is the identifier distributed to a registered object according to GB/T 17969. 1—2000.



A CA must not issue a certificate consisting of subjectAltNames and a null GeneralName. If the only subject identity in the certificate is a select name form (e.g. an email address), the subject's distinguished name must be null (a null sequence) and the subjectAltName extension must exist. If the subject string includes a null sequence, the subjectAltName extension must be marked as critical. If the subjectAltName extension appears, the sequence must at least contain one entry.

A name registration system should exist for every name form used in the GeneralName type, to ensure that any name used can identify an entity for the certificate issuer and the certificate user.

This extension can be either critical or non-critical, depending on the choice of the certificate issuer. The implementation that supports this extension is not required to process all name forms. If this extension is marked as critical, then it should at least be capable of identify and process one of the existing name forms; otherwise, this certificate should be regarded as invalid. Except for the previous limits, the certificate use system is allowed to ignore any names with unidentifiable or unsupported name forms. If the certificate subject item contains a directory name that identifies a subject without ambiguity, this item is recommended to be marked as non-critical.

NOTE: The usage of TYPE-IDENTIFIER type is described in Annex A and Annex C of GB/T 16262. 2—2006.

NOTE: If this extension exists and is marked as critical, the subject item of the certificate is allowed to contain null names (e.g. a "`0`" sequence of related distinguished name). In this situation, the subject can only be identified using the names in this extension or some extension names.

NOTE: For further explanation, please refer to RFC2459 4.2.1.7.




[level=6]
===== issuerAltName

This item contains one or multiple alternative names (any one of the multiple name forms) for the use of the certificate or the CRL issuer.

[level=7]
===== Definition

[source]
----
id-ce-issuerAltName OBJECT IDENTIFIER   ::= { id-ce 18 }
IssuerAltName   ::= GeneralName
----

[level=7]
===== Specification

This item can be either critical or non-critical, depending on the choice of the certificate issuer or the CRL issuer. The practical application that supports this extension is not required to be able to process all name forms. If this extension is marked as critical, then it should at least be able to identify and process one of the existing name forms; otherwise, this certificate should be regarded as invalid. Except for the previous limits, the certificate use system is allowed to ignore any names with unidentifiable or unsupported name forms. If the certificate issuer or the CRL issuer item contains a directory name clearly identifying the issuing authority, this item is recommended to be marked as non-critical.

If this extension exists and is marked as critical, the issuer item of the certificate or CRL can contain null names (e.g. correspond to a "`0`" sequence of the distinguished name). In this situation, the issuer can only be identified using names or some names in this extension. The issuer alternative names must be encoded according to the instruction of <<tbs-issuer>>.

[level=6]
===== subjectDirectoryAttributes

This item is any directory attribute value of the certificate subject conveying its expectations.

[level=7]
===== Definition

[source]
----
id-ce-subjectDirectoryAttributes OBJECT IDENTIFIER ::= { id-ce 9 }
SubjectDirectoryAttributes  ::= SEQUENCE SIZE (1..MAX) OF Attribute
AttributesSyntax            ::= SEQUENCE SIZE (1..MAX) OF Attribute
----

[level=7]
===== Specification

This extension is always non-critical.

[level=6]
===== basicConstraints

This item is used to identify whether or not a certificate subject is a CA and how long the possibly existing certification path through this CA is.

[level=7]
===== Definition

//TODO: the document had this before, which is wrong
//CABOOLEAN DEFAULT FALSE,
//pathLenConstraintINTEGER (0.. MAX) OPTIONAL}

[source]
----
id-ce-basicConstraints OBJECT IDENTIFIER ::= { id-ce 19 }
BasicConstraintsSyntax  ::= SEQUENCE{
  CA                  BOOLEAN DEFAULT FALSE,
  pathLenConstraint   INTEGER (0..MAX) OPTIONAL}
----

[level=7]
===== Specification


The CA field identifies whether or not this public key certificate can be used to verify a certificate signature.

The PathLenConstraint field is meaningful only when the CA is set to be TRUE. It gives the largest number of the CA certificates in the certification path after this certificate. 0 value indicates it can only issue certificates to end-entries but cannot issue subordinate CA certificates in the path. When PathLenConstraint appears, it must be larger than or equal to 0. If Path-LenConstraint doesn't appear in any certificates of the certification path, there is no limitation on the permissible length of the certification path.

This extension must be included in the CA certificate and must be critical; otherwise, the entity not authorized to be a CA can issue a certificate; meanwhile the certificate use system can unknowingly use such certificate.

If this extension exists and is marked as critical, then:

* If the value of the CA field is set to FALSE, then the key usage cannot contain the usage of keyCertSign; its public key should not be used to authenticate the certificate signature.

* If the value of the CA field is set to be TRUE, and pathLen Constraint exists, then the certificate use system should check whether the certification path processed is consistent with the value of pathLenConstraint.

NOTE: If this extension does not exist or is marked as non-critical and not approved by the certificate use system, this certificate is regarded as an end-user certificate by the system and cannot be used to authenticate the certificate signature.

NOTE: In order to restrict a certificate to one end-entity only, that is, not a CA, the issuer can contain an extension only with a null SEQUENCE value.



[level=6]
===== nameConstraints

This item is only used in one CA certificate. It designates a namespace, in which a certificate path is set and can be found in the subject name of the subsequent certificate.

[level=7]
===== Definition

[source]
----
id-ce-nameConstraints OBJECT IDENTIFIER ::= { id-ce 30 }

NameConstraintsSyntax ::= SEQUENCE {
  permittedSubtrees    [0]  GeneralSubtrees OPTIONAL,
  excludedSubtrees    [1]  GeneralSubtrees OPTIONAL }

GeneralSubtrees ::= SEQUENCE SIZE (1..MAX) OF GeneralSubtree
GeneralSubtree  ::= SEQUENCE {
  base          GeneralName,
  minimum    [0]  BaseDistance DEFAULT 0,
  maximum    [1]  BaseDistance OPTIONAL }

BaseDistance ::= INTEGER (0..MAX)
----

[level=7]
===== Specification


If the permittedSubtrees field and the excludedSubtrees field exist, each of them specifies one or multiple named subtrees and is defined by the name of the root of this subtree or the name of any node in the subtree. A subtree range is an area defined by upper and/or lower bounds. If permittedSubtrees exists, among all the certificates issued by the subject CA and the subsequent CA in certification path, only the certificates whose subject names are the same as the subject name specified in the permittedSubtrees field in the subtree can be accepted. If excludedSubtrees exists, among all the certificates issued by the subject CA or the subsequent CA in the certificate path, no certificate whose name is the same as the subject name specified in excludedSubtrees can be accepted. If PermittedSutrees and excludedSubtrees both exist and the namespace overlaps, the exclusion statement is preferred.

The naming format defined through the GeneralName field needs the name forms with a well-defined hierarchical structure to be applied to these fields.  The DirectoryName form can satisfy this need. The subtree being named using these naming formats correspond to the DIT subtree. There is no need to check and identify all possible naming formats. If this extension is marked as critical, and the naming format used in the base item cannot be identified in use by the certificate, the certificate should be processed as an unidentified critical item extension. If this extension is marked as non-critical, and the certificate cannot identify the naming format used in the base item, then this subtree specification can be ignored. When the certificate subject has multiple names of the same naming format (in the situation of the directory Name form, including the name of the certificate subject item, if not "`0`"), for the name constraint of the same name form, all the names should be checked for consistency.

The subject name or subject select name can be restricted. Apply the restriction only when confirmed name forms appear. If no type names exist in the certificate, the certificate can be accepted. When testing the certificate subject name for the consistency of naming format constraints, the extension should be processed even it is marked as non-critical.

The Minimum field specifies the upper bound of this area in the subtree. All final naming forms above the specified levels are not included in this area. The minimum value equal to "`0`" (default) corresponds to this base, that is, the top node of the subtree. For example, if the minimum is set to "`1`", then naming subtree does not contain the root node but only the lower node.

The Maximum field specifies the lower bound of this area in the subtree. No names with the final naming form below the specified level are contained in this area. The maximum value "`0`" corresponds to this base, that is, the top of the subtree. The non-existent maximum field points out that the lower limit value should not be applied to this area in the subtree. For example, if the maximum is set to "`1`", then the naming subtree does not contain all nodes except the subtree root nodes and its direct subordinates.

This Standard suggests it to be marked as critical; otherwise, the certificate user cannot check whether the subsequent certificate in the certificate path is in the naming domain designated by the issuing CA.

If this extension exists and is marked as critical, then the certificate user system should check whether the certification path processed is consistent with the value of this extension.

In this Standard, no name formats shall use the minimum or maximum fields; the minimum number is always 0, and the maximum number is always not filled.



[level=6]
===== policyConstraints

This item is used in the certificate issued by a CA. It restricts the path validation in two ways. It can be used to prohibit policy mapping or require each certificate in the path to contain an approved policy identifier.

[level=7]
===== Definition

[source]
----
id-ce-policyConstraints OBJECT IDENTIFIER ::= { id-ce 36 }

PolicyConstraints ::= SEQUENCE{
  requireExplicitPolicy   [0] SkipCerts OPTIONAL,
  inhibitPolicyMapping    [1] SkipCerts OPTIONAL }

SkipCerts ::= INTEGER (0..MAX)
----

[level=7]
===== Specification

If the requireExplicitPolicy field exists, and the certificate path contains a certificate issued by a designated CA, all certificates in this path are necessary to contain appropriate policy identifiers in their certificate extension items. An appropriate policy identifier is the identifier defined by the user in the certificate policy or the identifier of the policy equivalent to the declaration through policy mapping. The designated CA is an authority that contains this extension information (if the value of requireExplicitPolicy is "`0`") or the subsequent authority CA in the certification path (indicated by a non "`0`" value).

If the inhibitPolicyMapping value exists, it indicates no policy mapping is allowed among all the certificates in the certification path starting from the designated CA until the end of the certification path. The designated CA refers to the authority containing this extension information (if the value of inhibitPolicyMapping is "`0`") or the subsequent authority in the certification path (indicated by a non "`0`" value).

The SkipCerts type value indicates the number of certificates needed to be skipped in the certification path before a certain constraint becomes valid.

This extension can be either critical or non-critical, depending on the choice of the certificate issuer. This Standard suggests it to be marked as critical; otherwise the certificate user may not be able to correctly interpret the rules set by the authority.


[[crl-dist-points]]
[level=6]
===== CRLDistributionPoints

A CRL distribution points extension is used to identify how to obtain the CRL information. This extension is only used as a certificate extension. It can be used in an authority certificate, an end-entity public key certificate and an attribute certificate. This item designates the CRL distribution points or the certificate users' access points to find out whether or not the certificate has been revoked. The certificate user can obtain an CRL from the available distribution points or can obtain the current complete CRL from the authority directory item.

[level=7]
===== Definition

[source]
----
id-ce-CRLDistributionPoints OBJECT IDENTIFIER ::= { id-ce 31 }

cRLDistributionPoints ::= { CRLDistPointsSyntax }

CRLDistPointsSyntax   ::= SEQUENCE SIZE (1..MAX) OF DistributionPoint
DistributionPoint     ::= SEQUENCE {
  distributionPoint      [0]  DistributionPointName OPTIONAL,
  reasons                [1]  ReasonFlags OPTIONAL,
  cRLIssuer              [2]  GeneralNames OPTIONAL }

DistributionPointName ::= CHOICE {
  fullName                  [0]  GeneralNames,
  nameRelativeToCRLIssuer   [1]  RelativeDistinguishedName }

ReasonFlags ::= BITSTRING {
  unused                  (0),
  keyCompromise           (1),
  CACompromise            (2),
  affiliationChanged      (3),
  superseded              (4),
  cessationOfOperation    (5),
  certificateHold         (6) }
----

[level=7]
===== Specification



The distributionPoint field indicates how to obtain the CRL location. If this field is missing, the name of the distribution point is set to be the name of the CRL issuer.

When using the fullName alternative name or applying the default setting, the distribution point can have many name forms. The same name (at least use one of its name forms) should exist in the distrubutionPoint field of the distribution point extension issuing the CRL. The certificate use system is not required to be able to process all name forms. It can be allowed to process only one of the various name forms provided by the distribution point. If it cannot process any name forms of a certain distribution point but can obtain the necessary revocation information from another trusted source, for example, another distribution point or CA directory item, then the certificate use system can still use this certificate.

If the CRL distribution point is assigned to a directory name directly subject to the directory name of the CRL issuer, then only nameRelativeToCRLIssuer can be used. At this time the nameRelativeToCRLIssuer field transmits the distinguished name related to the CRL issuer directory name.

The Reasons field indicates the revocation reasons contained in this CRL. If there is no reason field, the corresponding CRL distribution point releases the CRL containing the item of this certificate (if this certificate has been revoked) and ignores the cause for revocation; otherwise, the reasons value indicates those revocation reasons contained in the corresponding CRL distribution points.

The CRLIssuer field identifies the authority issuing and signing the CRL. If this field is not present, the CRL issuer's name is regarded as the certificate issuer's name by default.

This extension can be either critical or non-critical, depending on the choice of the certificate issuer. It is suggested that this extension is set to be non-critical, but the CA and the application should support this extension.

If this extension is marked as critical, the CA should guarantee that the distribution point contains the revocation reason code keyCompromise and/or CA- Compromise. If the CRL is not searched and checked from a designated distribution point containing the reason code keyCompromise (to end-entity certificate) or CACompromise (to CA certificate) in the first place, the certificate use system will no longer use this certificate.  In the item where the distribution point distributes the CRL information for all revocation reason codes and all certificates issued by the CA (including CRLDistributionPoint as a critical extension), the CA does not need to release a complete CRL in the CA item.

If this extension is marked as non-critical, when the certificate use system cannot identify the type of this extension, then this system uses this certificate only in the following situations:

* It can obtain a complete CRL from the CA and check it (set a distribution point extension in the CRL to indicate the latest CRL is complete);

* The checking is not required to be revoked according to the local policy;

* Complete the revocation checking by taking other measures.

NOTE: It is possible for more than one CRL distributors to correspond to one certificate CRL issuer. Those CRL distributors along with the coordination of CA issuing are one aspect of the CA policy.

NOTE: Please refer to RFC2459 Section 5 for the application of the certificate revocation list (CRL).



[level=6]
===== inhibitAnyPolicy

This item designates a constraint which indicates that no policy is an explicit match for the certificate policies of all certificates in the certification path starting from the designated CA. The designated CA is either the subject CA of the certificate containing this extension (if the inhitAnyPolicy value is 0) or the subsequent authority CA in the certification path (designated by a non-0 value).

[level=7]
===== Definition

[source]
----
id-ce-inhibitAnyPolicy OBJECT IDENTIFIER ::= { id-ce 54 }
InhibitAnyPolicy    ::= SkipCerts
SkipCerts           ::= INTEGER(0..MAX)
----

[level=7]
===== Specification

This extension can be either critical or non-critical, depending on the choice of the certificate issuer. It is suggested to be marked as critical; otherwise the certificate user may not be able to correctly interpret the rules set by the authority CA.

[level=6]
===== 最新证书撤销列表freshestCRL

The freshest CRL extension is usually used as a certificate extension or used in the certificate issued to the authority or the user. This item identifies the CRL; the certificate user should contain the freshest revocation information for the CRL (e.g. the freshest CRL).

[level=7]
===== Definition

[source]
----
id-ce-CRL freshestCRL OBJECT IDENTIFIER ::= { id-ce 46 }
freshestCRL   ::= {CRLDistPointsSyntax}
----

[level=7]
===== Specification

This extension can be either critical or non-critical, depending on the choice of the certificate issuer. If the freshest CRL extension is critical, then the certificate use system does not use the freshest CRL certificate which is not revoked and checked in the first place. If the extension is marked as non-critical, the certificate use system can use the local method to decide if there is the need to check the freshest CRL.

[level=6]
===== IdentifyCode

A personal identity code extension is used to represent a personal identity number.

[level=7]
===== Definition

[source]
----
id-IdentifyCode OBJECT IDENTIFIER ::= { 1.2.156.10260.4.1.1 }

IdentifyCode ::= CHOICE {
  residenterCardNumber          [0]  PrintableString  OPTIONAL,
  militaryOfficerCardNumber     [1]  UTF8String  OPTIONAL,
  passportNumber                [2]  PrintableString  OPTIONAL
}
----

[level=7]
===== Specification

[source]
----
residenterCardNumber          --身份证号码
passportNumber                --护照号码
militaryOfficerCardNumber     --军官证号码
----

This extension is marked as non-critical.

[level=6]
===== InsuranceNumber

A personal social insurance number extension is used to represent a personal social insurance number.

[level=7]
===== Definition

[source]
----
ID-InsuranceNumber OBJECT IDENTIFIER ::= { 1.2.156.10260.4.1.2 }
InsuranceNumber     ::= PrintableString
----

[level=7]
===== Specification

This extension is marked as non-critical.

[level=6]
===== ICRegistrationNumber

An enterprise registration number extension is used to represent an enterprise registration number.

[level=7]
===== Definition

[source]
----
ID-ICRegistrationNumber OBJECT IDENTIFIER ::= { 1.2.156.10260.4.1.3 }
ICRegistrationNumber ::= PrintableString
----

[level=7]
===== Specification

This extension is marked as non-critical.

[level=6]
===== OrganizationCode

An organization code extension is used to represent an organization code.

[level=7]
===== Definition

[source]
----
ID-OrganizationCode OBJECT IDENTIFIER ::= { 1.2.156.10260.4.1.4 }
OrganizationCode ::= PrintableString
----

[level=7]
===== Specification

This extension is marked as non-critical.

[level=6]
===== TaxationNumber

An enterprise taxation number extension is used to represent an enterprise taxation number.

[level=7]
===== Definition

[source]
----
ID-TaxationNumber OBJECT IDENTIFIER ::= { 1.2.156.10260.4.1.5 }
TaxationNumber    ::= PrintableString
----

[level=7]
===== Specification

This extension is marked as non-critical.

===== PrivatelnternetExtensions id-pkix

[level=6]
===== General

This item defines two new extensions applied in the Internet public key infrastructure (PKI) for the use of application guidance in order to identify an online verification service that supports the CA.

[source]
----
id-pkix OBJECT IDENTIFIER ::=
                 { iso(1) identified-organization(3) dod(6) internet(l)
                          security(5) mechanisms(5) pkix(7) }
id-pe OBJECT IDENTIFIER   ::=  {  id-pkix  1  }
----

Each item is a sequence of IA5String values; each value represents a URL respectively. A URL directly confirms the location and format of the information as well as the way to obtain the information.

[level=6]
===== authorityInfoAccess

This item describes how the certificate issuer that contains this extension accesses the information and service of the CA. It includes the online verification service and the CA policy data. This extension can be included in the user certificate and the CA certificate and must be marked as non-critical.

[level=7]
===== Definition

[source]
----
id-pe-authorityInfoAccess OBJECT IDENTIFIER ::= { id-pe 1 }

AuthorityInfoAccessSyntax ::=
    SEQUENCE SIZE (1..MAX) OF AccessDescription

AccessDescription ::= SEQUENCE {
  accessMethod      OBJECT IDENTIFIER,
  accessLocation    GeneralName }

id-ad OBJECT IDENTIFIER           ::= { id-pkix 48 }
id-ad-calssuers OBJECT IDENTIFIER ::= { id-ad 2 }
id-ad-ocsp OBJECT IDENTIFIER      ::= { id-ad 1 }
----

[level=7]
===== Specification

Each portal of the sequence AuthorityInforAccessSyntax describes the format and location of the additional information of the CA issuing the certificate containing this extension. The type and format of the information is specified in the accessMethod field. The location of the information is specified in the accessLocation field. The retrieval mechanism can be indicated by accessMethod or explained by accessLocation.

This Standard defines an OID used for accessMethod. When the additional information indicates the CA issuing the certificate ranks higher than the certificate CA issuing this extension, use id-ad-calssuers OID.

When id-ad-calssuers appears as accessInfoType, the accessLocation field describes the form of the access protocol. The AccessLocation field is defined as GeneralName and has several forms: When the information can be accessed through http, ftp or ldap, accessLocation must be a uniformResourceldentifier type. When the information can be accessed through a directory access protocol, accessLocation must be a directoryName type. When the information can be accessed through an email, accessLocation must be a rfc822Name type.



[level=6]
===== SubjectInformationAccess

This item describes how the certificate subject accesses information and a service. If the subject is a CA, it includes the certification verification service and the CA policy data. If the subject is a user, it describes the type of service provided and how to access them; in this situation, the content in the extension field/item is defined in the explanation of the supported service protocol. This extension must be defined as non-critical.

[level=7]
===== Definition


[source]
----
id-pe-SubjectInformationAccess OBJECT IDENTIFIER ::= { id-pe 11 }

SubjectInfo AccessSyntax ::=
          SEQUENCE SIZE (1..MAX) OF AccessDescription

AccessDescription ::= SEQUENCE {
  accessMethod      OBJECT IDENTIFIER,
  accessLocation    GeneralName }
----

In addition, Annex A specifies the certificate structure. Annex B enumerates the standard digital certificate structure and specifies the criticality of the data item. Annex C enumerates the current general digital certificate structure used in China for reference. Annex D provides the certificate DER encoding for reference.

=== CRL Format

==== General

This Standard uses the distinguished encoding rules (DER) of the GB/T 16262 series of standard to encode all information in the following certificate revocation list items to form a distinguished certificate revocation list data structure. The ASN.1 DER encoding is an encoding system about the markup, length and value of each element.

=== CRL Data Structure

The ASN.1 of the CRL data structure is described as follows:

[source]
----
CertificateList ::= SEQUENCE {
  tbsCertList            TBSCertList,
  signatureAlgorithm     AlgorithmIdentifier,
  signatureValue        BIT STRING
}

TBSCertList ::= SEQUENCE {
  version                Version OPTIONAL,
                        --如果出现，必须是v2
  signature              AlgorithmIdentifier,
  issuer                Name,
  thisUpdate            Time,
  nextUpdate            Time OPTIONAL,
  revokedCertificates    SEQUENCE OF SEQUENCE {
    userCertificate        CertificateSerialNumber,
    revocationDate        Time,
    crlEntryExtensions     Extensions OPTIONAL
                          --如果出现，version必须是v2
  } OPTIONAL,
  crlExtensions      [0] EXPLICIT Extensions OPTIONAL
                        --如果出现，version必须是v2
}
----

The above CRL data structure is composed of three domains: tbsCertList, signatureAlgorithm and signatureValue. The meanings of those domains are as follows:

* The tbsCertList domain contains the subject name and the issuer name, the issuing date, the revoked certificate information and the CRL extension information.
* The signatureAlgorithm domain contains the algorithm identifiers used when the CA issues this CRL. The ASN. 1 structure of an algorithm identifier is as follows:
+
[source]
----
AlgorithmIdentifier ::= SEQUENCE {
  algorithm     OBJECT IDENTIFIER,
  parameters    ANY DEFINED BY algorithm OPTIONAL
}
----
An algorithm identifier is used to identify an algorithm, in which the OBJECT IDENTIFIER part identifies the specific algorithm.
The optional parameter content completely replies on the identified algorithm. The algorithm identifier of this domain must be the same with the signature algorithm item identified by the signature in tbsCertList. If the signature algorithm is SM2, there will be no parameters.


* The signatureValue domain contains the results of signing tbsCertList digitally. tbsCertList of the ASN. 1 DER encoding is used as the input of the digital signature, while the result of the signature is encoded as a BIT STRING type according to ASN. 1 and saved in the CRL signature value. If the signature algorithm is SM2, please refer to <<GMT0009>> for the SM2 algorithm signature data format.

==== TBSCertList and Data Structure

TBSCertList mainly contains the version number, the issuer, the effective date, the date of the next update, the signature algorithm, the key identifier of the issuing authority and the revoked certificate information. Some TBSCertList can also contain optional extensions. The syntax and semantics of these items are described in the following paragraphs of this section.

===== version

This optional item describes the version number of the encoded CRL. If the Extensions item is used, this item must exist and its value must be version 2 (represented by integer 1).

===== signature

This item contains the algorithm identifier used when the CA issues this CRL. This algorithm identifier must be the same as the algorithm identifier of the signatureAlgorithm item in CertificateList. Use the related algorithm reviewed and approved by the state cryptography administration department.

===== issuer

This item identifies the entity signing and issuing the CRL. It must contain a non-null distinguished name (DN-distinguished name). This item is defined as a Name type.

The issuer encoding rules are the same as those of <<tbs-issuer>>.

===== thisUpdate


This item indicates the issuing date of the CRL. It uses the UTCTime or GeneralizedTime encoding.

The CRL issuer complying with this Standard must set this time encoding to be the UTCTime type before 2049 (including 2049) and the GeneralizedTime type after 2050.

The UTCTime encoding rules are the same as that of <<validity-utctime>>.

The GeneralizedTime encoding rules are the same as those of <<validity-generalizedtime>>.


===== nextUpdate


This item indicates the time when the next CRL releases. The next CRL can be issued before this time but not after this time. Use the UTCTime encoding or the GeneralizedTime encoding.

The issuer complying with this Standard must contain the nextUpdate item in the issued CRL.

The issuer complying with this Standard must set the time encoding to be the UTCTime type before 2049 (including 2049) and the GeneralizedTime type after 2050.

The UTCTime encoding rules are the same as that of <<validity-utctime>>.

The GeneralizedTime encoding rules are the same as those of <<validity-generalizedtime>>.


===== Revoked Certificates

This domain indicates the revoked certificate serial number, the revocation time and the revocation reason.

If no revoked certificates are present, this item does not exist. If revoked certificates are present, list the serial number of the revoked certificate and specify the revocation date. crlEntryExtensions is described in <<crl-entry>>.


===== crlExtensions

This domain only appears in version 2. If present, this item is composed of one or more CRL extension sequences.

crlExtensions is described in <<crl-extensions>>.



[[crl-extensions]]
=== CRL扩展项及其数据结构

===== authorityKeyIdentifier

The issuing authority key identifier extension provides a way to identity the corresponding public key of the CRL signature private key. Use this extension when the issuer has multiple signature keys due to multiple keys coexisting or changes occurring. The identification can be based on the subject's key identifier or the issuer's name and serial number.

===== issuerAltName

This item contains one or more alternative names (can use any one of the multiple name forms) for the use of the CRL issuer.

===== crlNumber

The certificate revocation list number is a non-critical CRL extension indicating a monotonic increasing sequence with the designated CRL issuer and within the CRL scope. This extension allows users to conveniently ascertain when a specific CRL replaces another CRL. The certificate revocation list number also supports identifying the complete CRL and the Delta CRL of an attachment.

If the CRL issuer generates a Delta issuer along with a complete CRL within a specific scope, the complete CRL and the Delta CRL must share the same encoding sequence. If the complete CRL and the Delta CRL are issued at the same time, they must use the same certificate revocation list number and provide the same revocation information.

If a CRL issuer generates two CRLs (two complete CRLs, two Delta CRLs, or a complete CRL and a Delta CRL) at different times within a specific scope, those two CRLs cannot use the same certificate revocation list number. That is to say, if two CRLs have different thisUpdate domains, their certificate revocation list numbers have to be different.

The CRL number can be a long integer. The CRL verifier must be able to process a 20-byte certificate revocation list number. The CRL issuer complying with this Standard does not use a certificate revocation list number longer than 20 bytes.


[source]
----
id-ce-cRLNumber OBJECT IDENTIFIER ::= { id-ce 20 }
CRLNumber ::= INTEGER (0..MAX)
----


===== Delta CRL Indicator

A Delta CRL indicator is a critical CRL extension and indicates the CRL is a Delta CRL. A Delta CRL includes the renovation information since the last release, rather than contains all revocation information in a complete CRL. The use of a Delta CRL in some environments can significantly reduce network traffic and processing time.

A Delta CRL indicator extension contains a BaseCRLNumber type single value. A CRL number identifies the starting CRL used by this Delta CRL. The CRL issuer complying with this Standard must issue the datum reference CRL as a complete CRL. A Delta CRL contains all update revocation statuses. The combination of a Delta CRL and the datum reference CRL is equivalent to a complete CRL.

When the CRL issuer complying with this Standard generates a Delta CRL, this Delta CRL must contain a critical Delta CRL indicator extension.


[source]
----
id-ce-deltaCRLIndicator OBJECT IDENTIFIER ::= { id-ce 27 }
BaseCRLNumber ::= CRLNumber
----


===== Issuing Distribution Point

An issuing distribution point is a critical CRL extension indicating the distribution point and scope of a specific CRL.  It also indicates whether this CRL only contains revocation of user certificates, CA certificates revocation or a series of reason codes.

[source]
----
id-ce-issuingDistributionPoint OBJECT IDENTIFIER ::= { id-ce 28 }
IssuingDistributionPoint  ::= SEQUENCE {
  distributionPoint              [0] DistributionPointName OPTIONAL,
  onlyContainsUserCerts          [1] BOOLEAN DEFAULT FALSE,
  onlyContainsCACerts            [2] BOOLEAN DEFAULT FALSE,
  onlySomeReasons                [3] ReasonFlags OPTIONAL,
  indirectCRL                    [4] BOOLEAN DEFAULT FALSE,
  onlyContainsAttributeCerts     [5] BOOLEAN DEFAULT FALSE }
----

===== Freshest CRL

A freshest CRL shows how to obtain the Delta CRL information of a complete CRL. The CRL issuer complying with this Standard must mark this item as non-critical. This item does not appear in a Delta CRL.

The format of a freshest CRL extension is the same as that of the cRLDistributionPoints extension of a digital certificate. Please refer to <<crl-dist-points>>. However, the distribution point domain in this freshest CRL extension is of significance; meanwhile the Reasons domain and the cRLIssuer domain must be omitted.


[source]
----
id-ce-freshestCRL OBJECT IDENTIFIER ::=  { id-ce 46 }
FreshestCRL ::= CRLDistributionPoints
----

[[crl-entry]]
===== CRL Entry

[level=6]
===== Reason Code

A reason code is a non-critical extension indicating the reason for certificate revocation.

The code removeFromCRL (8) only applies to the Delta CRL. Other codes can apply to any CRLs.


[source]
----
id-ce-cRLReasons OBJECT IDENTIFIER ::= { id-ce 21 }

--reasonCode ::= { CRLReason }

CRLReason ::= ENUMERATED {
  unspecified           (0),
  keyCompromise          (1),
  cACompromise          (2),
  affiliationChanged    (3),
  superseded            (4),
  cessationOfOperation  (5),
  certificateHold        (6),
    -- 7不使用
  removeFromCRL         (8),
  privilegeWithdrawn    (9),
  aACompromise          (10) }
----

[level=6]
===== Invalidity Date

invalidity date is a non-critical extension indicating the time of knowing or suspecting a key being compromised or a certificate becoming invalid.

The GeneralizedTime contained in this domain must use the Greenwich Mean Time (GMT) and must be indicated according to the requirements of <<validity-generalizedtime>>.


[source]
----
id-ce-invalidityDate OBJECT IDENTIFIER ::= { id-ce 24 }
InvalidityDate ::= GeneralizedTime
----

[level=6]
===== Certificate Issuer

If present, the certificate issuer extension contains one or more names which correspond to the CRL entries and are obtained from a certificate issuer domain and/or issuer alternative name domain.

[source]
----
id-ce-certificateIssuer OBJECT IDENTIFIER ::= { id-ce 29 }
CertificateIssuer ::= GeneralNames
----



[appendix,obligation="normative"]
== Certificate Structure

=== Certificate Composition (See <<table-a1>>)

[[table-a1]]
.Certificate Structure
[cols="1a"]
|===

|TBSCertificate (TBSCertificate)
|Signature Algorithm (signatureAlgorithm)
|Signature Value  (signatureValue)

|===

=== TBSCertificate  (See <<table-a2>>)

[[table-a2]]
.TBSCertificate Structure
[cols="1a,1a,2a"]
|===
|Name
|Description
|Specification

|version  |Version number |
|serialNumber  |Serial number |
|signature  |Signature algorithm  |
|issuer  |Issuer |
|validity  |Validity |
|subject  |Subject |
|subjectPublicKeyInfo  |Subject public key information |
|issuerUniqueID  |Issuer unique identifier | Not used in this Standard
|subjectUniqueID  |Subject unique identifier   |Not used in this Standard
|extensions  |Extension | Defined based on the extensions in this Standard. See <<appendix-a3>>.

|===

[[appendix-a3]]
=== Standard Extension Field (See <<table-a3>>)

[[table-a3]]
.Standard Extension Field Structure
[cols="1a,1a,2a"]
|===
|Name
|Description
|Criticality

|authorityKeyIdentifier  |Authority key identifier   |Non-critical
|subjectKeyIdentifier  |Subject key identifier   |Non-critical
|keyUsage  |Key usage   |Critical for dual-certificate; non-critical for single certificate
|extKeyUsage  |Extended key usage  |Critical if key usage is only limited to the designated usages; otherwise non-critical.

|privateKeyUsagePeriod  | Private key usage period   |Non-critical
|certificatePolicies  | Certificate policies   |Non-critical

|policyMappings  | Policy mappings
|Critical when certificate user needs to correctly interpret the published rules set by CA; otherwise non-critical.

|subjectAltName  | Subject alternative name   |Non-critical
|issuerAltName  | Issuer alternative name   |Non-critical
|subjectDirectoryAttributes  | Subject directory attributes  |Non-critical
|basicConstraints  | Basic constraints   |Critical for CA certificate; non-critical for end-entry certificate.
|nameConstraints  | Name constraints |Critical if the certificate user system should check whether the certification path processed is consistent with the value of this extension; otherwise non-critical.
|policyConstraints  | Policy constraints
|Critical if a certificate user needs to correctly interpret the rules set by authority CA; otherwise non-critical.
|CRLDistributionPoints  | CRL distribution points  |Non-critical
|inhibitAnyPolicy  | Inhibit any policy
|Critical if a certificate user needs to correctly interpret the rules set by authority CA; otherwise non-critical.
|freshestCRL  | Freshest CRL  |Non-critical
|id-pkix  |Private Internet extension  |Non-critical
|authorityInfoAccess  |Authority information access   |Non-critical
|SubjectInformationAccess  |Subject information access  |Non-critical
|IdentityCardNumber  |Personal identification number   |Non-critical
|InsuranceNumber  |Personal social security number    |Non-critical
|ICRegistrationNumber  |Registration number  |Non-critical
|OrganizationCode  |Enterprise organization code  |Non-critical
|TaxationNumber  |Enterprise taxation number  |Non-critical

|===


[appendix,obligation="normative"]
== Certificate Structure Examples

=== User Certificate Structure Example (See <<table-b1>>）

[[table-b1]]
.User Certificate Structure
[cols="1a,2a"]
|===

2+|Version number  (version)
2+|Certificate serial number  (serialNumber)
2+|Signature algorithm identifier  (signature)
2+|Issuer name  (issuer)

.2+|Validity  (validity)
| Validity starting time
| Validity ending time

.6+|Subject name (subject)
| Country (countryName)
| State or province  (stateOrProvinceName)
| Locality name  (localityName)
| Organization name  (organizationName)
| Organization unit name  (organizationUnitName)
// TODO: This used to be "CommanName", should be CommonName
| User name  (CommonName)

2+|Subject pubic key information  (subjectPublicKeyInfo)
2+|Authority key identifier  (authorityKeyIdentifier)
2+|Subject key identifier  (subjectKeyIdentifier)
2+|CRL distribution points  (CRLDistributionPoints)

|===

=== Server Certificate Structure Example (See <<table-b2>>）

[[table-b2]]
.Server Certificate Structure
[cols="1a,2a"]
|===

2+|Version number  (version)
2+|Certificate serial number  (serialNumber)
2+|Signature algorithm identifier  (signature)
2+|Issuer name  (issuer)

.2+|Validity (validity)
| Validity starting time
| Validity ending time

.6+|Subject name (subject)
| Country (countryName)
| State or province  (stateOrProvinceName)
| Locality name  (localityName)
| Organization name  (organizationName)
| Organization unit name  (organizationUnitName)
// TODO: This used to be "CommanName", should be CommonName
| Server name (CommonName)

2+|Subject pubic key information  (subjectPublicKeyInfo)
2+|Authority key identifier  (authorityKeyIdentifier)
2+|Subject key identifier  (subjectKeyIdentifier)
2+|CRL distribution points  (CRLDistributionPoints)

|===



[appendix,obligation="normative"]
== Certificate Content Tables

This section contains a series of certificate content tables. Each table lists a special type certificate or a CRL's certificate content. The optional features which will be widely supported in the PKI system will also be identified. These attributes will be included in the issuer attributes. In practical applications, a certificate or a CRL may also contain a non-strict extension and other information in a local application, but the general PKI client will not process this additional information. In addition, the critical extensions not listed in a worksheet are not allowed to be used in the PKI certificates or the CRL contents in China.

The following certificate content tables are:

. The self-signed CA certificate content table, namely the root certificate content worksheet. It defines the mandatory and optional contents of the self-signed certificate. When the root of trust is confirmed, the CA in the PKI system releases the self-signed certificate.

. The secondary CA certificate content table. It defines the mandatory and optional contents of a secondary CA certificate.

. The End-entity signature certificate content table. It defines the mandatory and optional contents of the entity signature certificate issued by the CA in the PKI system. Its object is an end-entity, the private key of which is used for the signature and the public key of which will be used to verify the signature. The key of this certificate is generated at the client side when being issued and is owned privately by the client. Its private key should not be exported in the terminal end media.

. The end-entity cryptographic certificate content table. It defines the mandatory and optional contents of the entity cryptographic certificate issued by the CA in the PKI system. Its public key is used for enciphering data and its private key is used for deciphering data. The key is distributed by the key management center (KM) and its life cycle is controlled by the KM. Within the certificate validity period, if damaged, the medium can be recovered through the CA center through the normal process.

. The CRL content table. It defines the mandatory and optional contents of the CRL released by the CRL issuer.

An end-entity signature certificate and an encryption certificate should always appear in pairs. Their life cycles are managed by the CA center. A dual-purpose end-entity certificate (namely a single end-entity certificate used for both signature and encryption) is not suggested to be used due to its security and manageability problems.


=== Self-Signed CA Certificate Content Table (See <<table-c1>>）

[[table-c1]]
.TBS Structure
[cols="3a,1a,2a,3a"]
|===
|Domain
|Critical Item Identification
|Value
|Description

|Certificate  |||
|signature    |||
|AlgorithmIdentifier ||| Must match the signatureAlgorithm domain

.4+|algorithm
.4+|
2+|Choose amongst the following algorithms
|1.2.840.113549.1.1.5   |sha-1WithRSAEncryption
|1.2.840.113549.1.1.11  |sha256WithRSAEncryption
|1.2.156.10197.1.501    |SM3WithSM2Encryption

|parameters  ||  NULL  |This item is not needed when the SM2 algorithm is used.
|tbsCertificate |||  Content to be signed

|version ||  2 |Integer 2 used in version 3 certificate
|serialNumber  | |INTEGER  |For the only positive integer, see <<tbs-serial>>
|issuer |||
|Name  |||    Must be consistent with the subject DN
|RDNSequence |||
| RelativeDistinguishedName |||
|AttributeTypeAndValue  |||
|AttributeType    ||  OID |
|AttributeValue    ||| See  <<tbs-issuer>>
|validity |||
|NotBefore |||
|Time |||
|UtcTime    ||YYMMDDHHMMSSZ  |Applied to the years before 2049 (including 2049)
|generalTime    ||YYYYMMDDHHMMSSZ  |Applied to the years after 2049
|NotAfter |||
|Time |||
|UtcTime    ||YYMMDDHHMMSSZ  |Applied to the years before 2049 (including 2049)
|generalTime  ||YYYYMMDDHHMMSSZ  |Applied to the years after 2049
|subject  |||
|Name    |||  Must be consistent with the subject DN
|RDNSequence  |||
|RelativeDistinguishedName  |||
|AttributeTypeAndValue  |||
|AttributeType  ||  OID |
|AttributeValue  ||| See <<tbs-issuer>>
|subjectPublicKeyInfo  |||
|algorithm |||
|AlgorithmIdentifier  ||| Public Key Algorithm, can be RSA public key or elliptic-curve public key
.2+|algorithm
.2+|
|1.2.840.113549.1.1.1 |RSA
|1.2.156.10197.1.301  |SM2 elliptic-curve public key algorithm

.2+|parameters
.2+|
|NULL |RSA
|ECPublicKeySpec  |This will be the OID of the SM2 algorithm curve when the SM2 algorithm is used

|subjectPublicKey  | |BIT STRING  |For the RSA algorithm, the length should be at least 2,048 bits; for the SM2 algorithm, the public key should be at least 256 bits

4+|Mandatory Extensions
|subjectKeyIdentifier  |FALSE  ||Subject key identifier, for certificate path lookup
|KeyIdentifier  ||OCTET STRING  |The SHA-1 hashing algorithm digest of the public key value
|subjectInfoAccess  |FALSE  | |The object information storage includes a series of access methods. Only one storage method is defined in the CAE book.
|AccessDescription |||
|accessMethod  ||id-ad-caRepository (1.3.6.1.5.5.7.48.5)
|The self-signed certificate should at least include one example of the storage methods. This storage method includes that the URI names form a LDAP to access the designated location of the directory server. The certificate can also include that the URI names form a designated HTTP to visit a WEB server. Every URL should point to the location of the CA certificate.

|accessLocation |||
|GeneralName |||
|uniformResourceIdentifier  ||| Use "`ldap://`" or "`http://`" form
|basicConstraints  | TRUE ||
|cA    |TRUE ||
|KeyUsage  |TRUE ||
|Digital Signature digitalSignature    ||    0 |
|Non-Repudiation nonRepudiation    ||    0 |
|Key Encipherment  keyEncipherment   ||    0 |
|Data Encipherment dataEncipherment    ||    0 |
|Key Agreement key Agreement    ||    0 |
|Certificate Issuing KeyCertSign    ||    1 |
|Revocation List SignatureCRLSign    ||    1 |
|Encipher Only   encipherOnly    ||    0 |
|Decipher Only   decipherOnly    ||    0 |

4+|Optional Extension
|issuerAltName  |False  | |Any name type is fine, but only the most generally used name should be added here.
|GeneralNames |||
|GeneralName |||
|rfc822Name  ||IA5String  |PKI Administrator's email address

|===

=== Subordinate CA Certificate Content Table  (See <<table-c2>>)

[[table-c2]]
.Subordinate CA Certificate Content Table
[cols="3a,1a,2a,3a"]
|===
|Domain
|Critical Item Identification
|Value
|Description

|Certificate  |||
|signature    |||
|AlgorithmIdentifier ||| Must match the signatureAlgorithm domain

.4+|algorithm
.4+|
2+|选择下列算法
|1.2.840.113549.1.1.5   |sha-1WithRSAEncryption
|1.2.840.113549.1.1.11  |sha256WithRSAEncryption
|1.2.156.10197.1.501    |SM3WithSM2Encryption

|parameters  ||  NULL  |This item is not needed if when SM2 algorithm is used.
|tbsCertificate |||  Content to be signed

|version ||  2 |Integer 2 is used in version 3 certificate
|serialNumber  | |INTEGER  |Unique positive Integer
|issuer |||
|Name  |||    Must be consistent with the issuer subject DN
|RDNSequence |||
|RelativeDistinguishedName |||
|AttributeTypeAndValue  |||
|AttributeType    ||  OID |
|AttributeValue    ||| See <<tbs-issuer>>
|validity |||
|NotBefore |||
|Time |||
|UtcTime    ||YYMMDDHHMMSSZ  |Applied to the years before 2049 (including 2049)
|generalTime    ||YYYYMMDDHHMMSSZ  |Applied to the years after 2049
|NotAfter |||
|Time |||
|UtcTime    ||YYMMDDHHMMSSZ  |Applied to the years before 2049 (including 2049)
|generalTime  ||YYYYMMDDHHMMSSZ  |Applied to the years after 2049
|subject  |||
|Name    |||
|RDNSequence  |||
|RelativeDistinguishedName  |||
|AttributeTypeAndValue  |||
|AttributeType  ||  OID |
|AttributeValue  ||| See <<tbs-issuer>>
|subjectPublicKeyInfo  |||
|algorithm |||
|AlgorithmIdentifier  ||| Public Key Algorithm, can be RSA public key or elliptic-curve public key
.2+|algorithm
.2+|
|1.2.840.113549.1.1.1 |RSA
|1.2.156.10197.1.301  |SM2 elliptic-curve public key algorithm

.2+|parameters
.2+|
|NULL |RSA
|ECPublicKeySpec  |The OID of the SM2 algorithm curve

|subjectPublicKey  | |BIT STRING  |For the RSA algorithm, the length should be at least 2,048 bits; for the SM2 algorithm, the public key should be at least 256 bits

4+|Mandatory Extensions
|authorityKeyIdentifier  |FALSE  ||Issuer key identifier
|KeyIdentifier  ||OCTET STRING  |The SHA-1 digest value of the issuer public key value
|subjectKeyIdentifier  |FALSE  ||The subject key identifier used for certificate path lookup
|KeyIdentifier  ||OCTET STRING  |The SHA-1 hashing algorithm digest of the public key value
|basicConstraints  | TRUE ||
|cA    |TRUE ||
|KeyUsage  |TRUE ||
|Digital Signature digitalSignature    ||    0 |
|Non-Repudiation nonRepudiation    ||    0 |
|Key Encipherment  keyEncipherment   ||    0 |
|Data Encipherment dataEncipherment    ||    0 |
|Key Agreement key Agreement    ||    0 |
|Certificate Issuing KeyCertSign    ||    1 |
|Revocation List SignatureCRLSign    ||    1 |
|Encipher Only   encipherOnly    ||    0 |
|Decipher Only   decipherOnly    ||    (original is empty, or is it 0?) |

|certificatePolicies |||
|PolicyInformation |||
|policyIdentifier  | |OID  |The inclusion of policy qualifiers is discouraged
|CRLDistributionPoints |||
|DistributionPoint |||
|distributionPoint |||
|DistributionPointName |||
|fullName |||
|GeneralNames |||
|GeneralName |||
|directoryName |||
|Name |||
|RDNSequence |||
|RelativeDistinguished |||
|AttributeTypeAndV |||
|AttributeType  ||OID |
|AttributeValue |||
|uniformResourceIdentifier    ||| Use "`ldap://`" or "`http://`" form
|authorityInfoAccess  |FALSE ||
|AccessDescription  || |  Access method 1
|accessMethod  | |id-ad-calssuers (1.3.6.1.5.5.7.48.2) |
|accessLocation |||
|GeneralName |||
|uniformResourceIdentifier  |||    Use "`ldap://`" or "`http://`" form
|AccessDescription    ||| Access method 2
|accessMethod    ||id-ad-ocsp (1.3.6.1.5.5.7.48.1) |
|accessLocation |||
|GeneralName |||

|uniformResourceIdentifier  ||| Use "`ldap://`" or "`http://`" form
|subjectInfoAccess  |FALSE ||The object information storage contains a series of access methods; only one storage method is defined in the CA certificate.
|AccessDescription |||
|accessMethod  || id-ad-caRepository (1.3.6.1.5.5.7.48.5)
|A self-signed certificate should at least include one example of the storage methods. This storage method includes that the URI names form the LDAP to access the designated location of the directory server. The certificate can also include that the URI names form a designated HTTP to visit a WEB server. Every URL should point to the location of the CA certificate.

|accessLocation |||
|GeneralName |||
|uniformResourceIdentifier  |||  Use "`ldap://`" or "`http://`" form

4+|Optional Extension
|issuerAltName  |FALSE || Any name type is fine, but only the most generally used name should be added here.
|GeneralNames |||
|GeneralName  |||
|rfc822Name || IA5String  |PKI Administrator's email address
|FreshestCRL  |FALSE |  |This extension exists only when incremental blacklisting is in use.
|DistributionPoint  |||
|distributionPoint  |||
|DistributionPointName  |||
|fullName |||
|GeneralNames |||
|GeneralName  |||
|directoryName  |||
|Name |||
|RDNSequence  |||
|RelativeDistinguished  |||
|AttributeTypeAndV  |||
|AttributeType  ||OID |
|AttributeValue |||
|uniformResourceIdentifier ||| Use "`ldap://`" or "`http://`" form

|===



=== End-Entity Signature Certificate Content Table  (See <<table-c3>>)

[[table-c3]]
.End-Entity Signature Certificate Content Table
[cols="3a,1a,2a,3a"]
|===
|Domain
|Critical Item Identification
|Value
|Description

|Certificate  |||
|signature    |||
|AlgorithmIdentifier ||| Must match the signatureAlgorithm domain

.4+|algorithm
.4+|
2+|选择下列算法
|1.2.840.113549.1.1.5   |sha-1WithRSAEncryption
|1.2.840.113549.1.1.11  |sha256WithRSAEncryption
|1.2.156.10197.1.501    |SM3WithSM2Encryption

|parameters  ||  NULL  |
|tbsCertificate |||  Content to be signed

|version ||  2 |Integer 2 is used in version 3 certificate
|serialNumber  | |INTEGER  |Unique positive Integer
|issuer |||
|Name  |||    Must be consistent with the issuer subject DN
|RDNSequence |||
|RelativeDistinguishedName |||
|AttributeTypeAndValue  |||
|AttributeType    ||  OID |
|AttributeValue    ||| See <<tbs-issuer>>
|validity |||
|NotBefore |||
|Time |||
|UtcTime    ||YYMMDDHHMMSSZ  |Applied to the years before 2049 (including 2049)
|generalTime    ||YYYYMMDDHHMMSSZ  |Applied to the years after 2049
|NotAfter |||
|Time |||
|UtcTime    ||YYMMDDHHMMSSZ  |Applied to the years before 2049 (including 2049)
|generalTime  ||YYYYMMDDHHMMSSZ  |Applied to the years after 2049
|subject  |||
|Name    |||  Must be consistent with the subject DN
|RDNSequence  |||
|RelativeDistinguishedName  |||
|AttributeTypeAndValue  |||
|AttributeType  ||  OID |
|AttributeValue  ||| See <<tbs-issuer>>
|subjectPublicKeyInfo  |||
|algorithm |||
|AlgorithmIdentifier  ||| Public Key Algorithm, can be RSA public key or elliptic-curve public key
.2+|algorithm
.2+|
|1.2.840.113549.1.1.1 |RSA
|1.2.156.10197.1.301  |SM2 elliptic-curve public key algorithm

.2+|parameters
.2+|
|NULL |RSA
|ECPublicKeySpec  |The OID of SM2 algorithm curve

|subjectPublicKey  | |BIT STRING  |对RSA算法，模长至少应该是2 048位，对SM2箅法，公钥至少256位

4+|Mandatory Extensions
|authorityKeyIdentifier  |FALSE  ||Issuer key identifier
|keyIdentifier  ||OCTET STRING  |The SHA-1 hashing algorithm digest of the issuer public key value
|subjectKeyIdentifier  |FALSE  ||Subject key identifier, for certificate path lookup
|keyIdentifier  ||OCTET STRING  |The SHA-1 hashing algorithm digest of the public key value
|KeyUsage  |TRUE ||
|Digital Signature digitalSignature    ||    1 |
|Non-Repudiation nonRepudiation    ||    1 |
|Key Encipherment  keyEncipherment   ||    0 |
|Data Encipherment dataEncipherment    ||    0 |
|Key Agreement key Agreement    ||    0 |
|Certificate Issuing KeyCertSign    ||    0 |
|Revocation List SignatureCRLSign    ||    0 |
|Encipher Only   encipherOnly    ||  0 |
|Decipher Only   decipherOnly    ||    (original is empty, or is it 0?) |

|certificatePolicies  |  FALSE ||
|PolicyInformation  |||
|policyIdentifier ||OID  |The inclusion of policy qualifiers is discouraged
|CRLDistributionPoints  |||
|DistributionPoint  |||

|distributionPoint |||
|DistributionPointName |||
|fullName |||
|GeneralNames |||
|GeneralName |||
|directoryName |||
|Name |||
|RDNSequence |||
|RelativeDistinguished |||
|AttributeTypeAndV |||
|AttributeType    |OID ||
|AttributeValue |||
|uniformResourceIdentifier   ||| Use "`ldap://`" or "`http://`" form
|authorityInfoAccess  |FALSE ||
|AccessDescription  ||| Access method 1
|accessMethod  || id-ad-calssuers (1.3.6.1.5.5.7.48.2) |
|accessLocation |||
|GeneralName |||
|uniformResourceIdentifier  |||Use "`ldap://`" or "`http://`" form
|AccessDescription  |||Access method 2
|accessMethod  || id-ad-ocsp (1.3.6.1.5.5.7.48.1) |
|accessLocation |||
|GeneralName |||
|uniformResourceIdentifier  ||| Use "`ldap://`" or "`http://`" form

4+|Optional Extension
|extKeyUsage  |BOOLEAN  || Extension key usage
|KeyPurposeId  ||OID |
|issuerAltName |FALSE || Any name type is fine, but only the most generally used name should be added here.

|GeneralNames |||
|GeneralName |||
|rfc822Name  ||IA5String  |PKI Administrator's email address
|subjectAltName  |FALSE ||
|GeneralNames |||
|GeneralName |||
|rfc822Name  ||IA5String |
|dNSName    ||IA5String |
|iPAddress  ||IA5String |
|directoryName |||
|Name |||
|RDNSequence |||
|RelativeDistinguished |||
|AttributeTypeAndV |||
|AttributeType   || OID |
|AttributeValue  |||
|FreshestCRL |FALSE || This extension exists only when incremental blacklisting is in use.
|DistributionPoint  |||
|distributionPoint |||
|DistributionPointName |||
|fullName |||
|GeneralNames |||
|GeneralName |||
|directoryName |||
|Name |||
|RDNSequence |||
|RelativeDistinguished |||
|AttributeTypeAndV |||
|AttributeType  ||OID |
|AttributeValue |||
|uniformResourceIdentifier  ||| Use "`ldap://`" or "`http://`" form

|===


=== End-Entity Signature Certificate Content Table (See <<table-c4>>)

[[table-c4]]
.End-Entity Signature Certificate Content Table
[cols="3a,1a,2a,3a"]
|===
|Domain
|Critical Item Identification
|Value
|Description

|Certificate  |||
|signature    |||
|AlgorithmIdentifier ||| Must match the signatureAlgorithm domain

.4+|algorithm
.4+|
2+|选择下列算法
|1.2.840.113549.1.1.5   |sha-1WithRSAEncryption
|1.2.840.113549.1.1.11  |sha256WithRSAEncryption
|1.2.156.10197.1.501    |SM3WithSM2Encryption

|parameters  ||  NULL  |
|tbsCertificate |||  Content to be signed

|version ||  2 |Integer 2 is used in version 3 certificate
|serialNumber  | |INTEGER  |Unique positive Integer
|issuer |||
|Name  |||    Must be consistent with the issuer subject DN
|RDNSequence |||
|RelativeDistinguishedName |||
|AttributeTypeAndValue  |||
|AttributeType    ||  OID |
|AttributeValue    ||| See <<tbs-issuer>>
|validity |||
|NotBefore |||
|Time |||
|UtcTime    ||YYMMDDHHMMSSZ  |Applied to the years before 2049 (including 2049)
|generalTime    ||YYYYMMDDHHMMSSZ  |Applied to the years after 2049
|NotAfter |||
|Time |||
|UtcTime    ||YYMMDDHHMMSSZ  |Applied to the years before 2049 (including 2049)
|generalTime  ||YYYYMMDDHHMMSSZ  |Applied to the years after 2049
|subject  |||
|Name    |||
|RDNSequence  |||
|RelativeDistinguishedName  |||
|AttributeTypeAndValue  |||
|AttributeType  ||  OID |
|AttributeValue  ||| See <<tbs-issuer>>
|subjectPublicKeyInfo  |||
|algorithm |||
|AlgorithmIdentifier  ||| Public Key Algorithm, can be RSA public key or elliptic-curve public key
.2+|algorithm
.2+|
|1.2.840.113549.1.1.1 |RSA
|1.2.156.10197.1.301  |SM2 elliptic-curve public key algorithm

.2+|parameters
.2+|
|NULL |RSA
|ECPublicKeySpec  |The OID of SM2 algorithm curve

|subjectPublicKey  | |BIT STRING  |对RSA算法，模长至少应该是2 048位，对SM2箅法，公钥至少256位

4+|Mandatory Extensions

|authorityKeyIdentifier  |FALSE  ||  Issuer key identifier
|KeyIdentifier  ||  OCTET STRING  |The SHA-1 hashing algorithm digest of the issuer public key value
|subjectKeyIdentifier  |FALSE    ||Subject key identifier, for certificate path lookup
|KeyIdentifier  ||  OCTET STRING  |The SHA-1 hashing algorithm digest of the public key value
|KeyUsage  |TRUE ||
|Digital Signature digitalSignature  ||  0 |
|Non-Repudiation nonRepudiation    ||0 |
|Key Encipherment  keyEncipherment    ||1|
|Data Encipherment dataEncipherment    ||1|
|Key Agreement keyAgreement    ||1 |
|Certificate Issuing KeyCertSign  ||  0 |
|Revocation List SignatureCRLSign  ||  0 |
|Encipher Only   encipherOnly  ||  0 |
|Decipher Only   decipherOnly  ||  0 |
|certificatePolicies  |FALSE ||
|PolicyInformation |||
||policyIdentifier  ||  OID  |The inclusion of policy qualifiers is discouraged
|CRLDistributionPoints||

|DistributionPoint |||
|distributionPoint |||
|DistributionPointName |||
|fullName |||
|GeneralNames |||
|GeneralName |||
|directoryName |||
|Name |||
|RDNSequence |||
|RelativeDistinguished |||
|AttributeTypeAndV |||
|AttributeType    ||OID |
|AttributeValue |||
|uniformResourceIdentifier  |||  Use "`ldap://`" or "`http://`" form
|authorityInfoAccess  |FALSE ||
|AccessDescription  ||| Access method 1
|accessMethod  || id-ad-calssuers (1.3.6.1.5.5.7.48.2) |
|accessLocation  |||
|GeneralName |||
|uniformResourceIdentifier   |||    Use "`ldap://`" or "`http://`" form
|AccessDescription   |||    Access method 2
|accessMethod  || id-ad-ocsp (1.3.6.1.5.5.7.48.1) |
|accessLocation  |||
|GeneralName |||
|uniformResourceIdentifier   |||Use "`ldap://`" or "`http://`" form
4+|Optional Extension
|extKeyUsage  |BOOLEAN ||  Extension key usage
|KeyPurposeId  ||OID |
|issuerAltName  |FALSE  ||任Any name type is fine, but only the most generally used name should be added here.

|GeneralNames |||
|GeneralName |||
|r£c822Name    ||IA5String |PKI Administrator's email address
|subjectAltName  |FALSE ||
|GeneralNames |||
|GeneralName |||
|rfc822Name  ||IA5String |
|dnsName    ||IA5String |
|ipAddress  ||IA5String |
|directoryName |||
|Name |||
|RDNSequence |||
|RelativeDistinguished |||
|AttributeTypeAndV |||
|AttributeType  ||OID |
|AttributeValue |||
|FreshestCRL  |FALSE ||  This extension exists only when incremental blacklisting is in use.
|DistributionPoint |||
|distributionPoint |||
|DistributionPointName |||
|fullName |||
|GeneralNames |||
|GeneralName |||
|directoryName |||
|Name |||
|RDNSequence |||
|RelativeDistinguished |||
|AttributeTypeAndV |||
|AttributeType    || OID |
|AttributeValue |||
|uniformResourceIdentifier   |||Use "`ldap://`" or "`http://`" form

|===

=== Certificate Revocation List Content Table (See <<table-c5>>)

[[table-c5]]
.Certificate Revocation List Content Table
[cols="3a,1a,2a,3a"]
|===
|Domain
|Critical Item Identification
|Value
|Description

|CertificateList  |||
|signature    |||
|AlgorithmIdentifier ||| Must match the signatureAlgorithm domain

.4+|algorithm
.4+|
2+|选择下列算法
|1.2.840.113549.1.1.5   |sha-1WithRSAEncryption
|1.2.840.113549.1.1.11  |sha256WithRSAEncryption
|1.2.156.10197.1.501    |SM3WithSM2Encryption

|parameters  ||  NULL  |
|tbsCertList |||  Content to be signed

|version ||  2 |version 2 (Integer 1)
|issuer |||
|Name  |||    Must be consistent with the issuer subject DN
|RDNSequence |||
|RelativeDistinguishedName |||
|AttributeTypeAndValue  |||
|AttributeType    ||  OID |
|AttributeValue    ||| See <<tbs-issuer>>

|thisUpdate |||
|Time |||
|UtcTime    ||YYMMDDHHMMSSZ  |Applied to the years before 2049 (including 2049)
|generalTime    ||YYYYMMDDHHMMSSZ  |Applied to the years after 2049

|nextUpdate |||
|Time |||
|UtcTime    ||YYMMDDHHMMSSZ  |Applied to the years before 2049 (including 2049)
|generalTime  ||YYYYMMDDHHMMSSZ  |Applied to the years after 2049

|revokedCertificates  |||
|userCertificate ||  INTEGER | 被撤销证书的序列号
|revocationDate |||
|Time |||
|UtcTime  ||YYMMDDHHMMSSZ  |Applied to the years before 2049 (including 2049)
|generalTime  ||YYYYMMDDHHMMSSZ |Applied to the years after 2049

|crlEntryExtensions |||
|Extensions |||
|reasonCode  |FALSE  ||Use this extension when the reason of abolishement needs to be provided.
|CRLReason  ||| The main reason of this domain being used: key compromise, CA compromise, affiliation changed, suspended or cessation of operation. If the reason of abolishment is unknown, then this extension shouldn't be incremented. removeFromCRL can only applied to a Delta CRL. certificateHold is not suggested to be used.

|invalidityDate  |FALSE ||
|GeneralizedTime  ||YYYYMMDDHHMMSSZ |
|certificateIssuer  |FALSE ||
|GeneralNames |||
|GeneralName |||
|rfc822Name  || IA5String  |PKI Administrator's email address
|crlExtensions |||
|Extensions |||
|authorityKeyIdentifier  |FALSE ||  Issuer key identifier
|keyIdentifier  ||OCTET STRING  |The SHA-1 hashing algorithm digest of the issuer public key value
|issuerAltName  |FALSE ||任何名字类型都可以，但只有最通用 的名称才在这里加入
|GeneralNames |||
|GeneralName |||
|rfc822Name  ||IA5String  |PKI Administrator's email address
|CRLNumber  |FALSE  |INTEGER  |A monotonic increasing sequence; should be included in all CRLs.
|issuingDistributionPoint  |TRUE |OCTET STRING  |This item appears in partitioned CRLs. If CRL covers all certificates issued by their issuers, this item does not need to be included. The Standard does not suggest to use indirect CRLs or the CRLs that cannot cover all reason codes.
|distributionPoint  |||
|DistributionPointName  || |Used in a partitioned CRL; must be consistent with the distribution point extension value of the certificate.
|fullName  |||
|GeneralNames |||
|GeneralName |||
|directoryName |||
|Name |||
|RDNSequence |||
|RelativeDistinguished |||
|AttributeTypeAndV |||
|AttributeType   ||OID |
|Attribute Value |||
|uniformResourceIdentifier  ||IA5String  |Use "`ldap://`" or "`http://`" form
|onlyContainsUserCerts  ||BOOLEAN  |If set to true, then this CRL only covers entity certificates. (Note: if this value is true and meanwhile covers all entity certificates, then distributionPoint can be ignored.)
|onlyContainsCACerts    ||BOOLEAN  |If set to true, then this CRL only covers CA certificates. (Note: if this value is true and meanwhile covers all CA certificates, then distributionPoint can be ignored.)
|IndirectCRL  |FALSE  ||This Standard does not recommend to use an indirect CRL. If this CRL includes a certificate issued by an issuer that does not issue this CRL, this item must be set to true.
|FreshestCRL  |FALSE  ||This item is included when the incremental mode is enabled.
|DistributionPoint |||
|distributionPoint |||
|DistributionPointName |||
|fullName |||
|GeneralNames |||
|GeneralName |||
|directoryName |||
|Name |||
|RDNSequence |||
|RelativeDistinguished |||
|AttributeTypeAndV |||
|AttributeType  ||OID |
|AttributeValue |||
|uniformResourceIdentifier   |||  Use "`ldap://`" or "`http://`" form
|deltaCRLIndicator  |TRUE  ||This extension only appears in a Delta CRL.
|BaseCRLNumber  ||INTEGER  |Base CRL

|===


[appendix,obligation=informative]
== Digital Certificate Encoding Examples

=== RSA Digital Certificate Encoding

The content below will take X.509 version 3 certificate as the example. The certificate contains the following information:

[loweralpha]
. the serial number is 6565422187515605500000000000000000000;
. the certificate is signed with RSA and the sha1 hash algorithm;
. the issuer's distinguished name is CN=Certificate Center; C=CN;
. and the subject's distinguished name is CN=用户名字; ("user name"); OU=部门名称; ("department name"); O=组织名称; ("organization name"); S=省份名称; ("state name"); C=CN;
. the certificate was issued on August 7, 2003 and expired on August 6, 2004;
. the certificate contains a 1024-bit RSA public key;
. the certificate is an end entity certificate (not a CA certificate);
. the certificate includes an alternative subject name, is URL;
. the certificate includes an authority key identifier, subject KeyIdentifier and basic constraints extensions;
. the certificate includes a critical key usage extension specifying the public is intended for generation of digital signatures;
. the certificate includes an extend key usage extensions;
. the certificate includes a crl distributionpoints extensions.

[source]
----
0000 30 82 04 16  1046: SEQUENCE
0004 30 82 02 FE   766: .SEQUENCE
0008 a0 03           3: ..[0]
0010 02 01           1: ... INTEGER 2
                      : 02
0013 02 10          16: .. INTEGER 6565422187515605500000000000000000000
                      : 04 F0 74 4E 3D 72 65 06 C4 92 77 0A 5E 71 FI 5B
0031 30 0D          13: .. SEQUENCE
0033 06 09           9: ... OID 1.2.840.113549.1.1.5 shalwithRSAEncryption
                      : 2a 86 48 86 f7 Od 01 01 05
0044 05 00           0: ...NULL
0046 30 2A          42: .. SEQUENCE
0048 31 0B          11: ...SET
0050 30 09           9: ....SEQUENCE
0052 06 03           3: .....OID 2.5.4.6: C countryName
                      : 55 04 06
0057 13 02           2: .....PrintableString
                      : 43 4E
0061 31 IB          27: ...SET
0063 30 19          25: ....SEQUENCE
0065 06 03           3: .....OID 2.5.4.3: CN
                      : 55 04 03
0070 13 12          18: .....PrintableString 'Certificate Center'
                      : 43 65 72 74 69 66 69 63 61 74 65 20 43 65 6E 74 65 72
0090 30 1E          30: ..SEQUENCE
0092 17 0D          13: ...UTCTime  '030807063811Z'
                      : 30 33 30 38 30 37 30 36 33 38 31 31 5A
0107 17 0D          13: ...UTCTime  '040806063811Z'
                      : 30 34 30 38 30 36 30 36 31 38 31 31 5A
0122 30 7A         122: ..SEQUENCE
0124 31 IF          31: ...SET
0126 30 ID          29: ....SEQUENCE
0128 06 09          9 : .....OID 1.2.840.113549.1.9.1 emailAddress
                      : 2A 86 48 86 F7 OD 01 09 01
0139 16 10          16: .....IA5String 'name@mail.com.cn'
                      : 6E 61 6D 65 40 6D 61 69 6C 2E 63 6F 6D 2E 63 6E
0157 31 0B          11: ...SET
0159 30 09           9: ....SEQUENCE
0161 06 03           3: .....OID 2.5.4.6: C
                      : 55 04 06
0166 13 02           2: .....PrintableString 'CN'
                      : 43 4E
0170 31 11          17: ...SET
0172 30 0F          15: ....SEQUENCE
0174 06 03           3: .....OID 2.5.4.8: 'S'
                      : 55 04 08
0179 IE 08           8: .....BMPString '省份名称'
                      : 77 01 4E FD 54 OD 79 FO
0189 31 11          17: ...SET
0191 30 0F          15: ....SEQUENCE
0193 06 03           3: .....OID 2.5.4.10 'O'
                      : 55 04 0A
0198 IE 08           8: .....BMPString '组织名称'
                      : 7E C4 7E C7 54 0D 79 F0
0208 31 11          17: ...SET
0210 30 0F          15: ....SEQUENCE
0212 06 03           3: .....OID 2.5.4.11 'OU'
                      : 55 04 OB
0217 IE 08           8: .....BMPString '部门名称'
                      : 90 E8 95 E8 54 0D 79 F0
0227 31 11          17: ...SET
0229 30 0F          15: ....SEQUENCE
0231 06 03           3: .....OID 2.5.4.3 'CN'
                      : 55 04 03
0236 1E 08           8: .....BMPString '用户名字'
                      : 75 28 62 37 54 OD 5B 57
0246 30 81 9F      159: ..SEQUENCE
0249 30 0D          13: ...SEQUENCE
0251 06 09           9: .....OID 1.2.840.113549.1.1.1 rsaEncryption
                      : 2A 86 48 86 F7 OD 01 01 01
0262  05 00          0: .....NULL
0264 03 81 8D      141: ...  BIT STRING
                      : 00 (0 unused bits)
                        30 81 89 02 81 81 00 E0 57 4A 86 B6 52 91 85 14
                        6B 44 DB 9E E9 58 2B 9F 20 86 B0 C1 E5 A9 3B C8
                        75 08 9C 59 C2 A9 DD 8A 42 6B F8 FC 5F 8C 2E 53
                        C6 B5 FD A3 EE 55 3D 12 01 05 3B E2 76 CB 59 CE
                        AE 2C 7A 3D 4C 6B 83 58 39 OF 74 09 OD 61 OC 25
                        2D 4F 98 3A F2 C7 84 B2 73 OF 61 34 24 CF 29 B8
                        FA 5C 7E 5F 2A 42 B2 72 E6 BE CA DE 1D ED 3B D0 // TODO: 1D was LD??
                        0E 25 C3 87 C7 36 EF OE 4C 84 FA A7 00 44 8F 71
                        FE 46 62 A3 B0 C0 7D 02 03 01 00 01
0408 A3 82 01 6A   362: ..[3]
0412 30 82 01 66   358: ...SEQUENCE
0416 30 1F          31: ....SEQUENCE
0418 06 03           3: .....OID 2.5.29.35 authorityKeyIdentifier
                      : 55 1D 23
0423 04 18          24: .....OCTET STRING
                      : 30 16 80 14 E7 9F 11 9C EA 2D 20 54 05 34 24 D1
                        B2 53 23 67 D5 A7 E5 EB
0449 30 1D          29: ....SEQUENCE
0451 06 03           3: .....OID 2.5.29.14 subjectKeyIdentifier
                      : 55 1D 0E
0456 04 16          22: .....OCTET STRING
                      : 04 14 5C F5 D9 F7 EC 3E A2 BE B1 3B 7E 63 5E Cl 8B 2A 15 A3 BF 72
0480 30 0B          11: ....SEQUENCE
0482 06 03           3: .....OID 2.5.29.15 keyUsage
                      : 55 1D 0F
0487 04 04           4: .....OCTET STRING
                      : 03 02 03 F8
0493 30 1B          27: ....SEQUENCE
0495 06 03           3: .....OID 2.5.29.17 subjectAltName
                      : 55 1D 11
0500 04 14          20: .....OCTET STRING
                      : 30 12 81 10 73 69 6E 61 40 6D 61 69 6C 2E 63 6F
                        0D 2E 63 6E
0522 30 0C          12: ....SEQUENCE
0524 06 03           3: .....OID 2.5.29.19 basicConstraints
                      : 55 1D 13
0529 04 05           5: .....OCTET STRING
                      : 30 03 01 01 00
0536 30 3B          59: ....SEQUENCE
0538 06 03           3: .....OID 2.5.29.37 extKeyUsage
                      : 55 ID 25
0543 04 34          52: .....OCTET STRING
                      : 30 32 06 08 2B 06 01 05 05 07 03 01 06 08 2B 06
                        01 05 05 07 03 02 06 08 2B 06 01 05 05 07 03 03
                        06 08 2B 06 01 05 05 07 03 04 06 08 2B 06 01 05
                        07 03 08
0597 30 81 AE      174: ....SEQUENCE
0600 06 03           3: .....OID 2.5.29.31 cRLDistributionPoints
                      : 55 1D 1F
0605 04 81 A6      166: .....OCTET STRING
                      : 30 81 A3 30 7C A0 7A A0 78 A4 76 30 74 31 0D 30
                        0B 06 03 55 04 03 13 04 63 72 6C 30 31 0C 30 0A
                        06 03 55 04 0B 13 03 63 72 6C 31 0C 30 0A 06 03
                        55 04 0B 13 03 31 30 32 31 0A 30 08 06 03 55 04
                        0B 13 01 31 31 0D 30 0B 06 03 55 04 0A 13 04 4A
                        44 5A 59 31 0B 30 09 06 03 55 04 07 13 02 63 43
                        31 12 30 10 06 03 55 04 08 13 09 4A 69 6C 69 6E
                        39 39 34 38 31 0B 30 09 06 03 55 04 06 13 02 63
                        6E 30 23 A0 21 AO IF 86 1D 68 74 74 70 3A 2F 2F
                        63 72 6C 2E 63 6F 6D 2E 63 6E 2F 63 72 6C 2F 63
                        72 6C 2E 63 72 6C
0774 30 0D          13: .SEQUENCE
0776 06 09           9: .. OID 1.2.840.113549.1.1.5 shalwithRSAEncryption
                      : 2A 86 48 86 F7 OD 01 01 05
0787 05 00           0: ..NULL
0789 03 82 01 01   257: .BIT STRING
                      : 00 57 DF 8D D5 2A 06 56 84 3A FF IF 2A FD 96 F6
                        2C 36 D0 24 9C 74 32 C3 C5 BA BB B7 24 29 EB EC
                        60 E3 EC 90 D6 51 9E 54 42 4D IE 8C A0 79 4C 14
                        C8 E8 DC 20 A7 B9 0D 09 2A E8 9B 6C 19 44 B4 30
                        E7 BD F5 40 03 FB 14 89 5C E6 C5 47 E0 00 FA 17
                        45 61 0A C3 7C A3 7E B5 1D D6 A9 20 7E 70 89 91
                        4F F4 18 OE E6 C6 2A 7C 39 F4 8D 84 94 57 5B C3
                        B9 D5 12 C2 IB 54 6D F4 5D 88 6D AF 6C F7 28 DF
                        F9 23 58 BE 0B 1C 7A C9 83 82 80 98 98 F2 68 BF
                        BA 85 91 62 83 C4 E5 98 C2 A6 6B C2 B3 97 10 50
                        3B OE 9C 08 00 A4 34 FB 1B 41 AD 87 5E 2D EB EC
                        46 45 EA 9A FB 82 B4 B9 A5 AF 4A 61 88 5F A8 49
                        97 44 08 C2 3B 32 00 64 07 87 OB 2D 9D 7A 62 8F
                        44 56 F9 71 B9 89 10 B0 13 94 3ABD 33 6B 19 89
                        14 9F 58 E6 7D 0F 94 64 32 EA8E CE C8 77 65 C0
                        C5 D6 17 EA 71 A8 B8 D3 6B 50 D1 B3 86 28 C9 78
                        FE
----

=== SM2 Digital Certificate Encoding

The example provided below is a X.509 version 3 certificate, it contains the following information:

[loweralpha]
. the serial number is 64 57 00 b7 00 00 02 f6 (dec is 7230248512745636598) ;
. the certificate is signed with SM2 and the SM3 hash algorithm;
. the issuer's distinguished name is CN=OSCCA SM2 CA，C=CN;
. and the subject's distinguished name is CN=用户名字; ("user name"); OU=部门名称; ("department name"); O=组织名称; ("organization name"); S=省份名称; ("state name"); C=CN;
. the certificate was issued on March 22,2011 and expired on March 29,2014;
. the certificate contains a 256-bit SM2 EC public key;
. the certificate is an end entity certificate (not a CA certificate);
. the certificate includes an authority key identifier, subject KeyIdentifier and basic constraints   extension;
. the certificate includes a critical key usage extension specifying the public is intended for generation of digital signatures;
. the certificate includes an extend key usage extensions;

[source]
----
0000 30  200: SEQUENCE {
0004 30  1A5:   SEQUENCE {
0008 A0    3:   [0] {
000A 02    1:     INTEGER 2
            :   }
000D 02    8:   INTEGER
            :     64 57 00 B7 00 00 02 F6
0017 30    C:   SEQUENCE {
0019 06    8:     OBJECT IDENTIFIER '1 2 156 10197 1 501'
0023 05    0:
            :   }
0025 30   24:   SEQUENCE {
0027 31   15:     SET {
0029 30   13:       SEQUENCE {
002B 06    3:         OBJECT IDENTIFIER commonName (2 5 4 3)
0030 13    C:         PrintableString 'OSCCA SM2 CA'
            :       }
            :     }
003E 31    B:     SET {
0040 30    9:       SEQUENCE {
0042 06    3:         OBJECT IDENTIFIER countryName (2 5 4 6)
0045 13    2:         PrintableString 'CN'
            :       }
            :     }
            :   }
004B 30   1E:   SEQUENCE {
004D 17    D:     UTCTime '110322074444Z'
005C 17    D:     UTCTime '140329074400Z'
006B 30   52:     SEQUENCE {
006D 31   15:       SET {
006F 30   13:         SEQUENCE {
0071 06    3:           OBJECT IDENTIFIER commonName (2 5 4 3)
0076 0C    C:           UTF8String, 用户名字,
            :         }
            :       }
0084 31   15:       SET {
0086 30   13:         SEQUENCE {
0088 06    3:           OBJECT IDENTIFIER organizationalUnitName (2 5 4 11)
008D 0C    C:           UTF8String, 部门名称,
            :         }
            :       }
009B 31   15:       SET {
009D 30   13:         SEQUENCE {
009F 06    3:           OBJECT IDENTIFIER organizationName (2 5 4 10)
00A4 0C    C:           UTF8String, 组织名称,
            :         }
            :       }
00B2 31    B:       SET {
00B4 30    9:         SEQUENCE {
00B6 06    3:           OBJECT IDENTIFIER countryName (2 5 4 6)
00BB 13    2:           PrintableString 'CN'
            :         }
            :       }
            :     }
00BF 30   59:     SEQUENCE {
00C1 30   13:       SEQUENCE {
00C3 06    7:         OBJECT IDENTIFIER  ecPublicKey (1 2 840 10045 2 1)
OOCC 06    8:         OBJECT IDENTIFIER '1 2 156 10197 1 301'
            :       }
00D6 03   42:       BIT STRING 0 unused bits
            :         04 97 0A 71 9B CC 02 B4 6E E9 CC DF 59 2F 59 0B
            :         2D C7 5A AC B1 C7 B9 45 55 FE 07 E2 70 B3 83 9A
            :         4B EB 4C 37 A3 AD 5E FF BF 23 39 0C AD 36 9A EC
            :         58 B2 92 32 A0 CA 30 29 6F 0F FI F8 35 FI 52 F6
            :         76
            :     }
011A A3   90:     [3] {
011D 30   8D:       SEQUENCE {
0120 30    C:         SEQUENCE {
0122 06    3:           OBJECT IDENTIFIER basicConstraints (2 5 29 19)
0127 04    5:           OCTET STRING
            :             30 03 01 01 00
            :         }
012E 30   1D:         SEQUENCE {
0130 06    3:           OBJECT IDENTIFIER extKeyUsage (2 5 29 37)
0135 04   16:           OCTET STRING
            :             30 14 06 08 2B 06 01 05 05 07 03 02 06 08 2B 06
            :             01 05 05 07 03 04
            :         }
014D 30    B:         SEQUENCE {
014F 06    3:           OBJECT IDENTIFIER keyUsage (2 5 29 15)
0154 04    4:           OCTET STRING
            :             03 02 00 CO
            :         }
015A 30   11:         SEQUENCE {
015C 06    9:           OBJECT IDENTIFIER
            :             netscape-cert-type (2 16 840 1 113730 1 1)
0167 04    4:           OCTET STRING
            :             03 02 00 80
           8:         }
016D 30   1F:         SEQUENCE {
016F 06    3:           OBJECT IDENTIFIER authorityKeyIdentifier (2 5 29 35)
0174 04   18:           OCTET STRING
            :             30 16 80 14 8E 7B 6D F4 CB 16 BC 42 79 80 22 80
            :             92 49 97 1C EA BD D3 E5
            :         }
018E 30   1D:         SEQUENCE {
0190 06    3:           OBJECT IDENTIFIER subjectKeyIdentifier (2 5 29 14)
0195 04   16:           OCTET STRING
            :             04 14 IE 99 F3 37 A8 7E IF 5D C8 B5 C4 D9 F6 94
            :             2E A6 9C 24 9F 31
            :         }
            :       }
            :     }
            :   }
01 AD 30   C:   SEQUENCE {
01 AF 06   8:     OBJECT IDENTIFIER '1 2 156 10197 1 501'
01 B9 05   0:
            :   }
01 BB 03  47:   BIT STRING 0 unused bits
            :     30 44 02 20 50 37 93 B4 0E 0F 1C 9D 3E EE 7F 7E
            :     02 BE BD 3E DE 01 27 27 20 82 EE 8F 0F 6F E4 8A
            :     36 3F 26 B9 02 20 B5 70 08 46 76 7B 6F 27 43 6C
            :     BE D7 45 98 C4 5B 98 5C CB C8 1A 14 0E 2A 3B 03
            :     55 CA BE F1 72 F2
            : }
----


[bibliography]
== Reference documents
